// This file is part of Substrate.

// Copyright (C) Parity Technologies (UK) Ltd.
// SPDX-License-Identifier: Apache-2.0

// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// 	http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.


//! Autogenerated weights for `pallet_merkle_airdrop`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 49.1.0
//! DATE: 2025-12-17, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `coldbook.local`, CPU: `<UNKNOWN>`
//! WASM-EXECUTION: `Compiled`, CHAIN: `None`, DB CACHE: `1024`

// Executed Command:
// ./target/release/quantus-node
// benchmark
// pallet
// --runtime
// ./target/release/wbuild/quantus-runtime/quantus_runtime.wasm
// --pallet
// pallet_merkle_airdrop
// --extrinsic
// *
// --steps
// 50
// --repeat
// 20
// --output
// ./pallets/merkle-airdrop/src/weights_new.rs
// --template
// ./.maintain/frame-weight-template.hbs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]
#![allow(dead_code)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use core::marker::PhantomData;

/// Weight functions needed for `pallet_merkle_airdrop`.
pub trait WeightInfo {
	fn create_airdrop() -> Weight;
	fn fund_airdrop() -> Weight;
	fn claim(p: u32, ) -> Weight;
	fn delete_airdrop() -> Weight;
}

/// Weights for `pallet_merkle_airdrop` using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	/// Storage: `MerkleAirdrop::NextAirdropId` (r:1 w:1)
	/// Proof: `MerkleAirdrop::NextAirdropId` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `MerkleAirdrop::AirdropInfo` (r:0 w:1)
	/// Proof: `MerkleAirdrop::AirdropInfo` (`max_values`: None, `max_size`: Some(110), added: 2585, mode: `MaxEncodedLen`)
	fn create_airdrop() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `152`
		//  Estimated: `1489`
		// Minimum execution time: 39_000_000 picoseconds.
		Weight::from_parts(40_000_000, 1489)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	/// Storage: `MerkleAirdrop::AirdropInfo` (r:1 w:1)
	/// Proof: `MerkleAirdrop::AirdropInfo` (`max_values`: None, `max_size`: Some(110), added: 2585, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	fn fund_airdrop() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `578`
		//  Estimated: `3593`
		// Minimum execution time: 33_000_000 picoseconds.
		Weight::from_parts(35_000_000, 3593)
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	/// Storage: `MerkleAirdrop::Claimed` (r:1 w:1)
	/// Proof: `MerkleAirdrop::Claimed` (`max_values`: None, `max_size`: Some(68), added: 2543, mode: `MaxEncodedLen`)
	/// Storage: `MerkleAirdrop::AirdropInfo` (r:1 w:1)
	/// Proof: `MerkleAirdrop::AirdropInfo` (`max_values`: None, `max_size`: Some(110), added: 2585, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:2 w:2)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// The range of component `p` is `[0, 4096]`.
	fn claim(p: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `626`
		//  Estimated: `6196`
		// Minimum execution time: 39_000_000 picoseconds.
		Weight::from_parts(42_521_631, 6196)
			// Standard Error: 379
			.saturating_add(Weight::from_parts(298_012, 0).saturating_mul(p.into()))
			.saturating_add(T::DbWeight::get().reads(4_u64))
			.saturating_add(T::DbWeight::get().writes(4_u64))
	}
	/// Storage: `MerkleAirdrop::AirdropInfo` (r:1 w:1)
	/// Proof: `MerkleAirdrop::AirdropInfo` (`max_values`: None, `max_size`: Some(110), added: 2585, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	fn delete_airdrop() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `498`
		//  Estimated: `3593`
		// Minimum execution time: 31_000_000 picoseconds.
		Weight::from_parts(33_000_000, 3593)
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
}

// For backwards compatibility and tests.
impl WeightInfo for () {
	/// Storage: `MerkleAirdrop::NextAirdropId` (r:1 w:1)
	/// Proof: `MerkleAirdrop::NextAirdropId` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `MerkleAirdrop::AirdropInfo` (r:0 w:1)
	/// Proof: `MerkleAirdrop::AirdropInfo` (`max_values`: None, `max_size`: Some(110), added: 2585, mode: `MaxEncodedLen`)
	fn create_airdrop() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `152`
		//  Estimated: `1489`
		// Minimum execution time: 39_000_000 picoseconds.
		Weight::from_parts(40_000_000, 1489)
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
	/// Storage: `MerkleAirdrop::AirdropInfo` (r:1 w:1)
	/// Proof: `MerkleAirdrop::AirdropInfo` (`max_values`: None, `max_size`: Some(110), added: 2585, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	fn fund_airdrop() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `578`
		//  Estimated: `3593`
		// Minimum execution time: 33_000_000 picoseconds.
		Weight::from_parts(35_000_000, 3593)
			.saturating_add(RocksDbWeight::get().reads(2_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
	/// Storage: `MerkleAirdrop::Claimed` (r:1 w:1)
	/// Proof: `MerkleAirdrop::Claimed` (`max_values`: None, `max_size`: Some(68), added: 2543, mode: `MaxEncodedLen`)
	/// Storage: `MerkleAirdrop::AirdropInfo` (r:1 w:1)
	/// Proof: `MerkleAirdrop::AirdropInfo` (`max_values`: None, `max_size`: Some(110), added: 2585, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:2 w:2)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// The range of component `p` is `[0, 4096]`.
	fn claim(p: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `626`
		//  Estimated: `6196`
		// Minimum execution time: 39_000_000 picoseconds.
		Weight::from_parts(42_521_631, 6196)
			// Standard Error: 379
			.saturating_add(Weight::from_parts(298_012, 0).saturating_mul(p.into()))
			.saturating_add(RocksDbWeight::get().reads(4_u64))
			.saturating_add(RocksDbWeight::get().writes(4_u64))
	}
	/// Storage: `MerkleAirdrop::AirdropInfo` (r:1 w:1)
	/// Proof: `MerkleAirdrop::AirdropInfo` (`max_values`: None, `max_size`: Some(110), added: 2585, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	fn delete_airdrop() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `498`
		//  Estimated: `3593`
		// Minimum execution time: 31_000_000 picoseconds.
		Weight::from_parts(33_000_000, 3593)
			.saturating_add(RocksDbWeight::get().reads(2_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
}
