// This file is part of Substrate.

// Copyright (C) Parity Technologies (UK) Ltd.
// SPDX-License-Identifier: Apache-2.0

// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// 	http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.


//! Autogenerated weights for `pallet_multisig`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 49.1.0
//! DATE: 2026-01-20, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `coldbook.local`, CPU: `<UNKNOWN>`
//! WASM-EXECUTION: `Compiled`, CHAIN: `Some("dev")`, DB CACHE: `1024`

// Executed Command:
// target/release/quantus-node
// benchmark
// pallet
// --chain
// dev
// --pallet
// pallet_multisig
// --extrinsic
// *
// --steps
// 50
// --repeat
// 20
// --output
// pallets/multisig/src/weights.rs
// --template
// .maintain/frame-weight-template.hbs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]
#![allow(dead_code)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use core::marker::PhantomData;

/// Weight functions needed for `pallet_multisig`.
pub trait WeightInfo {
	fn create_multisig() -> Weight;
	fn propose(c: u32, ) -> Weight;
	fn approve(c: u32, ) -> Weight;
	fn approve_and_execute(c: u32, ) -> Weight;
	fn cancel(c: u32, ) -> Weight;
	fn remove_expired() -> Weight;
	fn claim_deposits() -> Weight;
}

/// Weights for `pallet_multisig` using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	/// Storage: `Multisig::GlobalNonce` (r:1 w:1)
	/// Proof: `Multisig::GlobalNonce` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `Multisig::Multisigs` (r:1 w:1)
	/// Proof: `Multisig::Multisigs` (`max_values`: None, `max_size`: Some(3306), added: 5781, mode: `MaxEncodedLen`)
	fn create_multisig() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `152`
		//  Estimated: `6771`
		// Minimum execution time: 178_000_000 picoseconds.
		Weight::from_parts(181_000_000, 6771)
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	/// Storage: `Multisig::Multisigs` (r:1 w:1)
	/// Proof: `Multisig::Multisigs` (`max_values`: None, `max_size`: Some(3306), added: 5781, mode: `MaxEncodedLen`)
	/// Storage: `Multisig::Proposals` (r:2 w:1)
	/// Proof: `Multisig::Proposals` (`max_values`: None, `max_size`: Some(13593), added: 16068, mode: `MaxEncodedLen`)
	/// The range of component `c` is `[0, 10140]`.
	fn propose(c: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `521`
		//  Estimated: `33126`
		// Minimum execution time: 163_000_000 picoseconds.
		Weight::from_parts(63_843_863, 33126)
			// Standard Error: 361
			.saturating_add(Weight::from_parts(165_427, 0).saturating_mul(c.into()))
			.saturating_add(T::DbWeight::get().reads(3_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	/// Storage: `Multisig::Multisigs` (r:1 w:1)
	/// Proof: `Multisig::Multisigs` (`max_values`: None, `max_size`: Some(3306), added: 5781, mode: `MaxEncodedLen`)
	/// Storage: `Multisig::Proposals` (r:1 w:1)
	/// Proof: `Multisig::Proposals` (`max_values`: None, `max_size`: Some(13593), added: 16068, mode: `MaxEncodedLen`)
	/// The range of component `c` is `[0, 10140]`.
	fn approve(c: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `781 + c * (1 ±0)`
		//  Estimated: `17058`
		// Minimum execution time: 14_000_000 picoseconds.
		Weight::from_parts(14_289_646, 17058)
			// Standard Error: 6
			.saturating_add(Weight::from_parts(383, 0).saturating_mul(c.into()))
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	/// Storage: `Multisig::Multisigs` (r:1 w:1)
	/// Proof: `Multisig::Multisigs` (`max_values`: None, `max_size`: Some(3306), added: 5781, mode: `MaxEncodedLen`)
	/// Storage: `Multisig::Proposals` (r:1 w:1)
	/// Proof: `Multisig::Proposals` (`max_values`: None, `max_size`: Some(13593), added: 16068, mode: `MaxEncodedLen`)
	/// The range of component `c` is `[0, 10140]`.
	fn approve_and_execute(c: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `749 + c * (1 ±0)`
		//  Estimated: `17058`
		// Minimum execution time: 17_000_000 picoseconds.
		Weight::from_parts(17_839_063, 17058)
			// Standard Error: 6
			.saturating_add(Weight::from_parts(769, 0).saturating_mul(c.into()))
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	/// Storage: `Multisig::Proposals` (r:1 w:1)
	/// Proof: `Multisig::Proposals` (`max_values`: None, `max_size`: Some(13593), added: 16068, mode: `MaxEncodedLen`)
	/// Storage: `Multisig::Multisigs` (r:1 w:1)
	/// Proof: `Multisig::Multisigs` (`max_values`: None, `max_size`: Some(3306), added: 5781, mode: `MaxEncodedLen`)
	/// The range of component `c` is `[0, 10140]`.
	fn cancel(c: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `749 + c * (1 ±0)`
		//  Estimated: `17058`
		// Minimum execution time: 12_000_000 picoseconds.
		Weight::from_parts(12_401_943, 17058)
			// Standard Error: 6
			.saturating_add(Weight::from_parts(527, 0).saturating_mul(c.into()))
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	/// Storage: `Multisig::Proposals` (r:1 w:1)
	/// Proof: `Multisig::Proposals` (`max_values`: None, `max_size`: Some(13593), added: 16068, mode: `MaxEncodedLen`)
	/// Storage: `Multisig::Multisigs` (r:1 w:1)
	/// Proof: `Multisig::Multisigs` (`max_values`: None, `max_size`: Some(3306), added: 5781, mode: `MaxEncodedLen`)
	fn remove_expired() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `779`
		//  Estimated: `17058`
		// Minimum execution time: 20_000_000 picoseconds.
		Weight::from_parts(20_000_000, 17058)
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	/// Storage: `Multisig::Proposals` (r:6 w:5)
	/// Proof: `Multisig::Proposals` (`max_values`: None, `max_size`: Some(13593), added: 16068, mode: `MaxEncodedLen`)
	/// Storage: `Multisig::Multisigs` (r:1 w:1)
	/// Proof: `Multisig::Multisigs` (`max_values`: None, `max_size`: Some(3306), added: 5781, mode: `MaxEncodedLen`)
	fn claim_deposits() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1891`
		//  Estimated: `97398`
		// Minimum execution time: 80_000_000 picoseconds.
		Weight::from_parts(82_000_000, 97398)
			.saturating_add(T::DbWeight::get().reads(7_u64))
			.saturating_add(T::DbWeight::get().writes(6_u64))
	}
}

// For backwards compatibility and tests.
impl WeightInfo for () {
	/// Storage: `Multisig::GlobalNonce` (r:1 w:1)
	/// Proof: `Multisig::GlobalNonce` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `Multisig::Multisigs` (r:1 w:1)
	/// Proof: `Multisig::Multisigs` (`max_values`: None, `max_size`: Some(3306), added: 5781, mode: `MaxEncodedLen`)
	fn create_multisig() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `152`
		//  Estimated: `6771`
		// Minimum execution time: 178_000_000 picoseconds.
		Weight::from_parts(181_000_000, 6771)
			.saturating_add(RocksDbWeight::get().reads(2_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
	/// Storage: `Multisig::Multisigs` (r:1 w:1)
	/// Proof: `Multisig::Multisigs` (`max_values`: None, `max_size`: Some(3306), added: 5781, mode: `MaxEncodedLen`)
	/// Storage: `Multisig::Proposals` (r:2 w:1)
	/// Proof: `Multisig::Proposals` (`max_values`: None, `max_size`: Some(13593), added: 16068, mode: `MaxEncodedLen`)
	/// The range of component `c` is `[0, 10140]`.
	fn propose(c: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `521`
		//  Estimated: `33126`
		// Minimum execution time: 163_000_000 picoseconds.
		Weight::from_parts(63_843_863, 33126)
			// Standard Error: 361
			.saturating_add(Weight::from_parts(165_427, 0).saturating_mul(c.into()))
			.saturating_add(RocksDbWeight::get().reads(3_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
	/// Storage: `Multisig::Multisigs` (r:1 w:1)
	/// Proof: `Multisig::Multisigs` (`max_values`: None, `max_size`: Some(3306), added: 5781, mode: `MaxEncodedLen`)
	/// Storage: `Multisig::Proposals` (r:1 w:1)
	/// Proof: `Multisig::Proposals` (`max_values`: None, `max_size`: Some(13593), added: 16068, mode: `MaxEncodedLen`)
	/// The range of component `c` is `[0, 10140]`.
	fn approve(c: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `781 + c * (1 ±0)`
		//  Estimated: `17058`
		// Minimum execution time: 14_000_000 picoseconds.
		Weight::from_parts(14_289_646, 17058)
			// Standard Error: 6
			.saturating_add(Weight::from_parts(383, 0).saturating_mul(c.into()))
			.saturating_add(RocksDbWeight::get().reads(2_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
	/// Storage: `Multisig::Multisigs` (r:1 w:1)
	/// Proof: `Multisig::Multisigs` (`max_values`: None, `max_size`: Some(3306), added: 5781, mode: `MaxEncodedLen`)
	/// Storage: `Multisig::Proposals` (r:1 w:1)
	/// Proof: `Multisig::Proposals` (`max_values`: None, `max_size`: Some(13593), added: 16068, mode: `MaxEncodedLen`)
	/// The range of component `c` is `[0, 10140]`.
	fn approve_and_execute(c: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `749 + c * (1 ±0)`
		//  Estimated: `17058`
		// Minimum execution time: 17_000_000 picoseconds.
		Weight::from_parts(17_839_063, 17058)
			// Standard Error: 6
			.saturating_add(Weight::from_parts(769, 0).saturating_mul(c.into()))
			.saturating_add(RocksDbWeight::get().reads(2_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
	/// Storage: `Multisig::Proposals` (r:1 w:1)
	/// Proof: `Multisig::Proposals` (`max_values`: None, `max_size`: Some(13593), added: 16068, mode: `MaxEncodedLen`)
	/// Storage: `Multisig::Multisigs` (r:1 w:1)
	/// Proof: `Multisig::Multisigs` (`max_values`: None, `max_size`: Some(3306), added: 5781, mode: `MaxEncodedLen`)
	/// The range of component `c` is `[0, 10140]`.
	fn cancel(c: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `749 + c * (1 ±0)`
		//  Estimated: `17058`
		// Minimum execution time: 12_000_000 picoseconds.
		Weight::from_parts(12_401_943, 17058)
			// Standard Error: 6
			.saturating_add(Weight::from_parts(527, 0).saturating_mul(c.into()))
			.saturating_add(RocksDbWeight::get().reads(2_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
	/// Storage: `Multisig::Proposals` (r:1 w:1)
	/// Proof: `Multisig::Proposals` (`max_values`: None, `max_size`: Some(13593), added: 16068, mode: `MaxEncodedLen`)
	/// Storage: `Multisig::Multisigs` (r:1 w:1)
	/// Proof: `Multisig::Multisigs` (`max_values`: None, `max_size`: Some(3306), added: 5781, mode: `MaxEncodedLen`)
	fn remove_expired() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `779`
		//  Estimated: `17058`
		// Minimum execution time: 20_000_000 picoseconds.
		Weight::from_parts(20_000_000, 17058)
			.saturating_add(RocksDbWeight::get().reads(2_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
	/// Storage: `Multisig::Proposals` (r:6 w:5)
	/// Proof: `Multisig::Proposals` (`max_values`: None, `max_size`: Some(13593), added: 16068, mode: `MaxEncodedLen`)
	/// Storage: `Multisig::Multisigs` (r:1 w:1)
	/// Proof: `Multisig::Multisigs` (`max_values`: None, `max_size`: Some(3306), added: 5781, mode: `MaxEncodedLen`)
	fn claim_deposits() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1891`
		//  Estimated: `97398`
		// Minimum execution time: 80_000_000 picoseconds.
		Weight::from_parts(82_000_000, 97398)
			.saturating_add(RocksDbWeight::get().reads(7_u64))
			.saturating_add(RocksDbWeight::get().writes(6_u64))
	}
}
