// This file is part of Substrate.

// Copyright (C) Parity Technologies (UK) Ltd.
// SPDX-License-Identifier: Apache-2.0

// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// 	http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.


//! Autogenerated weights for `pallet_multisig`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 49.1.0
//! DATE: 2026-01-27, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `coldbook.local`, CPU: `<UNKNOWN>`
//! WASM-EXECUTION: `Compiled`, CHAIN: `Some("dev")`, DB CACHE: `1024`

// Executed Command:
// ./target/release/quantus-node
// benchmark
// pallet
// --chain=dev
// --pallet=pallet_multisig
// --extrinsic=*
// --steps=50
// --repeat=20
// --output=./pallets/multisig/src/weights.rs
// --template=./.maintain/frame-weight-template.hbs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]
#![allow(dead_code)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use core::marker::PhantomData;

/// Weight functions needed for `pallet_multisig`.
pub trait WeightInfo {
	fn create_multisig() -> Weight;
	fn propose(c: u32, e: u32, ) -> Weight;
	fn approve(c: u32, ) -> Weight;
	fn approve_and_execute(c: u32, ) -> Weight;
	fn cancel(c: u32, ) -> Weight;
	fn remove_expired() -> Weight;
	fn claim_deposits(p: u32, ) -> Weight;
	fn dissolve_multisig() -> Weight;
}

/// Weights for `pallet_multisig` using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	/// Storage: `Multisig::GlobalNonce` (r:1 w:1)
	/// Proof: `Multisig::GlobalNonce` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `Multisig::Multisigs` (r:1 w:1)
	/// Proof: `Multisig::Multisigs` (`max_values`: None, `max_size`: Some(6924), added: 9399, mode: `MaxEncodedLen`)
	fn create_multisig() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `152`
		//  Estimated: `10389`
		// Minimum execution time: 192_000_000 picoseconds.
		Weight::from_parts(197_000_000, 10389)
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	/// Storage: `Multisig::Multisigs` (r:1 w:1)
	/// Proof: `Multisig::Multisigs` (`max_values`: None, `max_size`: Some(6924), added: 9399, mode: `MaxEncodedLen`)
	/// Storage: `Multisig::Proposals` (r:201 w:201)
	/// Proof: `Multisig::Proposals` (`max_values`: None, `max_size`: Some(13557), added: 16032, mode: `MaxEncodedLen`)
	/// The range of component `c` is `[0, 10140]`.
	/// The range of component `e` is `[0, 200]`.
	fn propose(_c: u32, e: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `458 + e * (215 ±0)`
		//  Estimated: `17022 + e * (16032 ±0)`
		// Minimum execution time: 40_000_000 picoseconds.
		Weight::from_parts(162_343_032, 17022)
			// Standard Error: 41_034
			.saturating_add(Weight::from_parts(14_232_109, 0).saturating_mul(e.into()))
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().reads((1_u64).saturating_mul(e.into())))
			.saturating_add(T::DbWeight::get().writes(2_u64))
			.saturating_add(T::DbWeight::get().writes((1_u64).saturating_mul(e.into())))
			.saturating_add(Weight::from_parts(0, 16032).saturating_mul(e.into()))
	}
	/// Storage: `Multisig::Multisigs` (r:1 w:1)
	/// Proof: `Multisig::Multisigs` (`max_values`: None, `max_size`: Some(6924), added: 9399, mode: `MaxEncodedLen`)
	/// Storage: `Multisig::Proposals` (r:1 w:1)
	/// Proof: `Multisig::Proposals` (`max_values`: None, `max_size`: Some(13557), added: 16032, mode: `MaxEncodedLen`)
	/// The range of component `c` is `[0, 10140]`.
	fn approve(c: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `766 + c * (1 ±0)`
		//  Estimated: `17022`
		// Minimum execution time: 14_000_000 picoseconds.
		Weight::from_parts(16_119_988, 17022)
			// Standard Error: 42
			.saturating_add(Weight::from_parts(766, 0).saturating_mul(c.into()))
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	/// Storage: `Multisig::Multisigs` (r:1 w:1)
	/// Proof: `Multisig::Multisigs` (`max_values`: None, `max_size`: Some(6924), added: 9399, mode: `MaxEncodedLen`)
	/// Storage: `Multisig::Proposals` (r:1 w:1)
	/// Proof: `Multisig::Proposals` (`max_values`: None, `max_size`: Some(13557), added: 16032, mode: `MaxEncodedLen`)
	/// The range of component `c` is `[0, 10140]`.
	fn approve_and_execute(c: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `734 + c * (1 ±0)`
		//  Estimated: `17022`
		// Minimum execution time: 25_000_000 picoseconds.
		Weight::from_parts(33_804_547, 17022)
			// Standard Error: 105
			.saturating_add(Weight::from_parts(802, 0).saturating_mul(c.into()))
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	/// Storage: `Multisig::Proposals` (r:1 w:1)
	/// Proof: `Multisig::Proposals` (`max_values`: None, `max_size`: Some(13557), added: 16032, mode: `MaxEncodedLen`)
	/// Storage: `Multisig::Multisigs` (r:1 w:1)
	/// Proof: `Multisig::Multisigs` (`max_values`: None, `max_size`: Some(6924), added: 9399, mode: `MaxEncodedLen`)
	/// The range of component `c` is `[0, 10140]`.
	fn cancel(c: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `734 + c * (1 ±0)`
		//  Estimated: `17022`
		// Minimum execution time: 19_000_000 picoseconds.
		Weight::from_parts(24_824_223, 17022)
			// Standard Error: 65
			.saturating_add(Weight::from_parts(117, 0).saturating_mul(c.into()))
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	/// Storage: `Multisig::Multisigs` (r:1 w:1)
	/// Proof: `Multisig::Multisigs` (`max_values`: None, `max_size`: Some(6924), added: 9399, mode: `MaxEncodedLen`)
	/// Storage: `Multisig::Proposals` (r:1 w:1)
	/// Proof: `Multisig::Proposals` (`max_values`: None, `max_size`: Some(13557), added: 16032, mode: `MaxEncodedLen`)
	fn remove_expired() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `764`
		//  Estimated: `17022`
		// Minimum execution time: 20_000_000 picoseconds.
		Weight::from_parts(24_000_000, 17022)
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	/// Storage: `Multisig::Proposals` (r:201 w:200)
	/// Proof: `Multisig::Proposals` (`max_values`: None, `max_size`: Some(13557), added: 16032, mode: `MaxEncodedLen`)
	/// Storage: `Multisig::Multisigs` (r:1 w:1)
	/// Proof: `Multisig::Multisigs` (`max_values`: None, `max_size`: Some(6924), added: 9399, mode: `MaxEncodedLen`)
	/// The range of component `p` is `[1, 200]`.
	fn claim_deposits(p: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `625 + p * (237 ±0)`
		//  Estimated: `17022 + p * (16032 ±0)`
		// Minimum execution time: 24_000_000 picoseconds.
		Weight::from_parts(27_900_496, 17022)
			// Standard Error: 31_493
			.saturating_add(Weight::from_parts(13_930_528, 0).saturating_mul(p.into()))
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().reads((1_u64).saturating_mul(p.into())))
			.saturating_add(T::DbWeight::get().writes(1_u64))
			.saturating_add(T::DbWeight::get().writes((1_u64).saturating_mul(p.into())))
			.saturating_add(Weight::from_parts(0, 16032).saturating_mul(p.into()))
	}
	/// Storage: `Multisig::Multisigs` (r:1 w:1)
	/// Proof: `Multisig::Multisigs` (`max_values`: None, `max_size`: Some(6924), added: 9399, mode: `MaxEncodedLen`)
	/// Storage: `Multisig::Proposals` (r:1 w:0)
	/// Proof: `Multisig::Proposals` (`max_values`: None, `max_size`: Some(13557), added: 16032, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:0)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	fn dissolve_multisig() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `538`
		//  Estimated: `17022`
		// Minimum execution time: 20_000_000 picoseconds.
		Weight::from_parts(20_000_000, 17022)
			.saturating_add(T::DbWeight::get().reads(3_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
}

// For backwards compatibility and tests.
impl WeightInfo for () {
	/// Storage: `Multisig::GlobalNonce` (r:1 w:1)
	/// Proof: `Multisig::GlobalNonce` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `Multisig::Multisigs` (r:1 w:1)
	/// Proof: `Multisig::Multisigs` (`max_values`: None, `max_size`: Some(6924), added: 9399, mode: `MaxEncodedLen`)
	fn create_multisig() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `152`
		//  Estimated: `10389`
		// Minimum execution time: 192_000_000 picoseconds.
		Weight::from_parts(197_000_000, 10389)
			.saturating_add(RocksDbWeight::get().reads(2_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
	/// Storage: `Multisig::Multisigs` (r:1 w:1)
	/// Proof: `Multisig::Multisigs` (`max_values`: None, `max_size`: Some(6924), added: 9399, mode: `MaxEncodedLen`)
	/// Storage: `Multisig::Proposals` (r:201 w:201)
	/// Proof: `Multisig::Proposals` (`max_values`: None, `max_size`: Some(13557), added: 16032, mode: `MaxEncodedLen`)
	/// The range of component `c` is `[0, 10140]`.
	/// The range of component `e` is `[0, 200]`.
	fn propose(_c: u32, e: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `458 + e * (215 ±0)`
		//  Estimated: `17022 + e * (16032 ±0)`
		// Minimum execution time: 40_000_000 picoseconds.
		Weight::from_parts(162_343_032, 17022)
			// Standard Error: 41_034
			.saturating_add(Weight::from_parts(14_232_109, 0).saturating_mul(e.into()))
			.saturating_add(RocksDbWeight::get().reads(2_u64))
			.saturating_add(RocksDbWeight::get().reads((1_u64).saturating_mul(e.into())))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
			.saturating_add(RocksDbWeight::get().writes((1_u64).saturating_mul(e.into())))
			.saturating_add(Weight::from_parts(0, 16032).saturating_mul(e.into()))
	}
	/// Storage: `Multisig::Multisigs` (r:1 w:1)
	/// Proof: `Multisig::Multisigs` (`max_values`: None, `max_size`: Some(6924), added: 9399, mode: `MaxEncodedLen`)
	/// Storage: `Multisig::Proposals` (r:1 w:1)
	/// Proof: `Multisig::Proposals` (`max_values`: None, `max_size`: Some(13557), added: 16032, mode: `MaxEncodedLen`)
	/// The range of component `c` is `[0, 10140]`.
	fn approve(c: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `766 + c * (1 ±0)`
		//  Estimated: `17022`
		// Minimum execution time: 14_000_000 picoseconds.
		Weight::from_parts(16_119_988, 17022)
			// Standard Error: 42
			.saturating_add(Weight::from_parts(766, 0).saturating_mul(c.into()))
			.saturating_add(RocksDbWeight::get().reads(2_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
	/// Storage: `Multisig::Multisigs` (r:1 w:1)
	/// Proof: `Multisig::Multisigs` (`max_values`: None, `max_size`: Some(6924), added: 9399, mode: `MaxEncodedLen`)
	/// Storage: `Multisig::Proposals` (r:1 w:1)
	/// Proof: `Multisig::Proposals` (`max_values`: None, `max_size`: Some(13557), added: 16032, mode: `MaxEncodedLen`)
	/// The range of component `c` is `[0, 10140]`.
	fn approve_and_execute(c: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `734 + c * (1 ±0)`
		//  Estimated: `17022`
		// Minimum execution time: 25_000_000 picoseconds.
		Weight::from_parts(33_804_547, 17022)
			// Standard Error: 105
			.saturating_add(Weight::from_parts(802, 0).saturating_mul(c.into()))
			.saturating_add(RocksDbWeight::get().reads(2_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
	/// Storage: `Multisig::Proposals` (r:1 w:1)
	/// Proof: `Multisig::Proposals` (`max_values`: None, `max_size`: Some(13557), added: 16032, mode: `MaxEncodedLen`)
	/// Storage: `Multisig::Multisigs` (r:1 w:1)
	/// Proof: `Multisig::Multisigs` (`max_values`: None, `max_size`: Some(6924), added: 9399, mode: `MaxEncodedLen`)
	/// The range of component `c` is `[0, 10140]`.
	fn cancel(c: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `734 + c * (1 ±0)`
		//  Estimated: `17022`
		// Minimum execution time: 19_000_000 picoseconds.
		Weight::from_parts(24_824_223, 17022)
			// Standard Error: 65
			.saturating_add(Weight::from_parts(117, 0).saturating_mul(c.into()))
			.saturating_add(RocksDbWeight::get().reads(2_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
	/// Storage: `Multisig::Multisigs` (r:1 w:1)
	/// Proof: `Multisig::Multisigs` (`max_values`: None, `max_size`: Some(6924), added: 9399, mode: `MaxEncodedLen`)
	/// Storage: `Multisig::Proposals` (r:1 w:1)
	/// Proof: `Multisig::Proposals` (`max_values`: None, `max_size`: Some(13557), added: 16032, mode: `MaxEncodedLen`)
	fn remove_expired() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `764`
		//  Estimated: `17022`
		// Minimum execution time: 20_000_000 picoseconds.
		Weight::from_parts(24_000_000, 17022)
			.saturating_add(RocksDbWeight::get().reads(2_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
	/// Storage: `Multisig::Proposals` (r:201 w:200)
	/// Proof: `Multisig::Proposals` (`max_values`: None, `max_size`: Some(13557), added: 16032, mode: `MaxEncodedLen`)
	/// Storage: `Multisig::Multisigs` (r:1 w:1)
	/// Proof: `Multisig::Multisigs` (`max_values`: None, `max_size`: Some(6924), added: 9399, mode: `MaxEncodedLen`)
	/// The range of component `p` is `[1, 200]`.
	fn claim_deposits(p: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `625 + p * (237 ±0)`
		//  Estimated: `17022 + p * (16032 ±0)`
		// Minimum execution time: 24_000_000 picoseconds.
		Weight::from_parts(27_900_496, 17022)
			// Standard Error: 31_493
			.saturating_add(Weight::from_parts(13_930_528, 0).saturating_mul(p.into()))
			.saturating_add(RocksDbWeight::get().reads(2_u64))
			.saturating_add(RocksDbWeight::get().reads((1_u64).saturating_mul(p.into())))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
			.saturating_add(RocksDbWeight::get().writes((1_u64).saturating_mul(p.into())))
			.saturating_add(Weight::from_parts(0, 16032).saturating_mul(p.into()))
	}
	/// Storage: `Multisig::Multisigs` (r:1 w:1)
	/// Proof: `Multisig::Multisigs` (`max_values`: None, `max_size`: Some(6924), added: 9399, mode: `MaxEncodedLen`)
	/// Storage: `Multisig::Proposals` (r:1 w:0)
	/// Proof: `Multisig::Proposals` (`max_values`: None, `max_size`: Some(13557), added: 16032, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:0)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	fn dissolve_multisig() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `538`
		//  Estimated: `17022`
		// Minimum execution time: 20_000_000 picoseconds.
		Weight::from_parts(20_000_000, 17022)
			.saturating_add(RocksDbWeight::get().reads(3_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
}
