// This file is part of Substrate.

// Copyright (C) Parity Technologies (UK) Ltd.
// SPDX-License-Identifier: Apache-2.0

// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// 	http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.


//! Autogenerated weights for `pallet_multisig`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 49.1.0
//! DATE: 2026-01-19, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `coldbook.local`, CPU: `<UNKNOWN>`
//! WASM-EXECUTION: `Compiled`, CHAIN: `Some("dev")`, DB CACHE: `1024`

// Executed Command:
// target/release/quantus-node
// benchmark
// pallet
// --chain
// dev
// --pallet
// pallet_multisig
// --extrinsic
// *
// --steps
// 50
// --repeat
// 20
// --output
// pallets/multisig/src/weights.rs
// --template
// .maintain/frame-weight-template.hbs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]
#![allow(dead_code)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use core::marker::PhantomData;

/// Weight functions needed for `pallet_multisig`.
pub trait WeightInfo {
	fn create_multisig() -> Weight;
	fn propose() -> Weight;
	fn approve() -> Weight;
	fn approve_and_execute() -> Weight;
	fn cancel() -> Weight;
	fn remove_expired() -> Weight;
	fn claim_deposits() -> Weight;
}

/// Weights for `pallet_multisig` using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	/// Storage: `Multisig::GlobalNonce` (r:1 w:1)
	/// Proof: `Multisig::GlobalNonce` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `Multisig::Multisigs` (r:1 w:1)
	/// Proof: `Multisig::Multisigs` (`max_values`: None, `max_size`: Some(3302), added: 5777, mode: `MaxEncodedLen`)
	fn create_multisig() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `152`
		//  Estimated: `6767`
		// Minimum execution time: 181_000_000 picoseconds.
		Weight::from_parts(193_000_000, 6767)
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	/// Storage: `Multisig::Multisigs` (r:1 w:1)
	/// Proof: `Multisig::Multisigs` (`max_values`: None, `max_size`: Some(3302), added: 5777, mode: `MaxEncodedLen`)
	/// Storage: `Multisig::Proposals` (r:1 w:1)
	/// Proof: `Multisig::Proposals` (`max_values`: None, `max_size`: Some(13593), added: 16068, mode: `MaxEncodedLen`)
	fn propose() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `461`
		//  Estimated: `17058`
		// Minimum execution time: 162_000_000 picoseconds.
		Weight::from_parts(168_000_000, 17058)
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	/// Storage: `Multisig::Multisigs` (r:1 w:1)
	/// Proof: `Multisig::Multisigs` (`max_values`: None, `max_size`: Some(3302), added: 5777, mode: `MaxEncodedLen`)
	/// Storage: `Multisig::Proposals` (r:1 w:1)
	/// Proof: `Multisig::Proposals` (`max_values`: None, `max_size`: Some(13593), added: 16068, mode: `MaxEncodedLen`)
	fn approve() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `807`
		//  Estimated: `17058`
		// Minimum execution time: 15_000_000 picoseconds.
		Weight::from_parts(17_000_000, 17058)
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	/// Storage: `Multisig::Multisigs` (r:1 w:1)
	/// Proof: `Multisig::Multisigs` (`max_values`: None, `max_size`: Some(3302), added: 5777, mode: `MaxEncodedLen`)
	/// Storage: `Multisig::Proposals` (r:1 w:1)
	/// Proof: `Multisig::Proposals` (`max_values`: None, `max_size`: Some(13593), added: 16068, mode: `MaxEncodedLen`)
	fn approve_and_execute() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `775`
		//  Estimated: `17058`
		// Minimum execution time: 18_000_000 picoseconds.
		Weight::from_parts(20_000_000, 17058)
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	/// Storage: `Multisig::Proposals` (r:1 w:1)
	/// Proof: `Multisig::Proposals` (`max_values`: None, `max_size`: Some(13593), added: 16068, mode: `MaxEncodedLen`)
	/// Storage: `Multisig::Multisigs` (r:1 w:1)
	/// Proof: `Multisig::Multisigs` (`max_values`: None, `max_size`: Some(3302), added: 5777, mode: `MaxEncodedLen`)
	fn cancel() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `775`
		//  Estimated: `17058`
		// Minimum execution time: 12_000_000 picoseconds.
		Weight::from_parts(14_000_000, 17058)
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	/// Storage: `Multisig::Proposals` (r:1 w:1)
	/// Proof: `Multisig::Proposals` (`max_values`: None, `max_size`: Some(13593), added: 16068, mode: `MaxEncodedLen`)
	/// Storage: `Multisig::Multisigs` (r:1 w:1)
	/// Proof: `Multisig::Multisigs` (`max_values`: None, `max_size`: Some(3302), added: 5777, mode: `MaxEncodedLen`)
	fn remove_expired() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `775`
		//  Estimated: `17058`
		// Minimum execution time: 20_000_000 picoseconds.
		Weight::from_parts(21_000_000, 17058)
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	/// Storage: `Multisig::Proposals` (r:6 w:5)
	/// Proof: `Multisig::Proposals` (`max_values`: None, `max_size`: Some(13593), added: 16068, mode: `MaxEncodedLen`)
	/// Storage: `Multisig::Multisigs` (r:1 w:1)
	/// Proof: `Multisig::Multisigs` (`max_values`: None, `max_size`: Some(3302), added: 5777, mode: `MaxEncodedLen`)
	fn claim_deposits() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1887`
		//  Estimated: `97398`
		// Minimum execution time: 79_000_000 picoseconds.
		Weight::from_parts(81_000_000, 97398)
			.saturating_add(T::DbWeight::get().reads(7_u64))
			.saturating_add(T::DbWeight::get().writes(6_u64))
	}
}

// For backwards compatibility and tests.
impl WeightInfo for () {
	/// Storage: `Multisig::GlobalNonce` (r:1 w:1)
	/// Proof: `Multisig::GlobalNonce` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `Multisig::Multisigs` (r:1 w:1)
	/// Proof: `Multisig::Multisigs` (`max_values`: None, `max_size`: Some(3302), added: 5777, mode: `MaxEncodedLen`)
	fn create_multisig() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `152`
		//  Estimated: `6767`
		// Minimum execution time: 181_000_000 picoseconds.
		Weight::from_parts(193_000_000, 6767)
			.saturating_add(RocksDbWeight::get().reads(2_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
	/// Storage: `Multisig::Multisigs` (r:1 w:1)
	/// Proof: `Multisig::Multisigs` (`max_values`: None, `max_size`: Some(3302), added: 5777, mode: `MaxEncodedLen`)
	/// Storage: `Multisig::Proposals` (r:1 w:1)
	/// Proof: `Multisig::Proposals` (`max_values`: None, `max_size`: Some(13593), added: 16068, mode: `MaxEncodedLen`)
	fn propose() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `461`
		//  Estimated: `17058`
		// Minimum execution time: 162_000_000 picoseconds.
		Weight::from_parts(168_000_000, 17058)
			.saturating_add(RocksDbWeight::get().reads(2_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
	/// Storage: `Multisig::Multisigs` (r:1 w:1)
	/// Proof: `Multisig::Multisigs` (`max_values`: None, `max_size`: Some(3302), added: 5777, mode: `MaxEncodedLen`)
	/// Storage: `Multisig::Proposals` (r:1 w:1)
	/// Proof: `Multisig::Proposals` (`max_values`: None, `max_size`: Some(13593), added: 16068, mode: `MaxEncodedLen`)
	fn approve() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `807`
		//  Estimated: `17058`
		// Minimum execution time: 15_000_000 picoseconds.
		Weight::from_parts(17_000_000, 17058)
			.saturating_add(RocksDbWeight::get().reads(2_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
	/// Storage: `Multisig::Multisigs` (r:1 w:1)
	/// Proof: `Multisig::Multisigs` (`max_values`: None, `max_size`: Some(3302), added: 5777, mode: `MaxEncodedLen`)
	/// Storage: `Multisig::Proposals` (r:1 w:1)
	/// Proof: `Multisig::Proposals` (`max_values`: None, `max_size`: Some(13593), added: 16068, mode: `MaxEncodedLen`)
	fn approve_and_execute() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `775`
		//  Estimated: `17058`
		// Minimum execution time: 18_000_000 picoseconds.
		Weight::from_parts(20_000_000, 17058)
			.saturating_add(RocksDbWeight::get().reads(2_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
	/// Storage: `Multisig::Proposals` (r:1 w:1)
	/// Proof: `Multisig::Proposals` (`max_values`: None, `max_size`: Some(13593), added: 16068, mode: `MaxEncodedLen`)
	/// Storage: `Multisig::Multisigs` (r:1 w:1)
	/// Proof: `Multisig::Multisigs` (`max_values`: None, `max_size`: Some(3302), added: 5777, mode: `MaxEncodedLen`)
	fn cancel() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `775`
		//  Estimated: `17058`
		// Minimum execution time: 12_000_000 picoseconds.
		Weight::from_parts(14_000_000, 17058)
			.saturating_add(RocksDbWeight::get().reads(2_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
	/// Storage: `Multisig::Proposals` (r:1 w:1)
	/// Proof: `Multisig::Proposals` (`max_values`: None, `max_size`: Some(13593), added: 16068, mode: `MaxEncodedLen`)
	/// Storage: `Multisig::Multisigs` (r:1 w:1)
	/// Proof: `Multisig::Multisigs` (`max_values`: None, `max_size`: Some(3302), added: 5777, mode: `MaxEncodedLen`)
	fn remove_expired() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `775`
		//  Estimated: `17058`
		// Minimum execution time: 20_000_000 picoseconds.
		Weight::from_parts(21_000_000, 17058)
			.saturating_add(RocksDbWeight::get().reads(2_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
	/// Storage: `Multisig::Proposals` (r:6 w:5)
	/// Proof: `Multisig::Proposals` (`max_values`: None, `max_size`: Some(13593), added: 16068, mode: `MaxEncodedLen`)
	/// Storage: `Multisig::Multisigs` (r:1 w:1)
	/// Proof: `Multisig::Multisigs` (`max_values`: None, `max_size`: Some(3302), added: 5777, mode: `MaxEncodedLen`)
	fn claim_deposits() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1887`
		//  Estimated: `97398`
		// Minimum execution time: 79_000_000 picoseconds.
		Weight::from_parts(81_000_000, 97398)
			.saturating_add(RocksDbWeight::get().reads(7_u64))
			.saturating_add(RocksDbWeight::get().writes(6_u64))
	}
}
