// This file is part of Substrate.

// Copyright (C) Parity Technologies (UK) Ltd.
// SPDX-License-Identifier: Apache-2.0

// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// 	http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.


//! Autogenerated weights for `pallet_mining_rewards`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 53.0.0
//! DATE: 2026-06-07, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `Q-Beasts-MacBook-Air.local`, CPU: `<UNKNOWN>`
//! WASM-EXECUTION: `Compiled`, CHAIN: `None`, DB CACHE: `1024`

// Executed Command:
// ./target/release/quantus-node
// benchmark
// pallet
// --pallet=pallet_mining_rewards
// --steps=50
// --repeat=20
// --runtime=./target/release/wbuild/quantus-runtime/quantus_runtime.wasm
// --genesis-builder=runtime
// --extrinsic=*
// --wasm-execution=compiled
// --heap-pages=4096
// --template=./.maintain/frame-weight-template.hbs
// --output=./pallets/mining-rewards/src/weights.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]
#![allow(dead_code)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use core::marker::PhantomData;

/// Weight functions needed for `pallet_mining_rewards`.
pub trait WeightInfo {
	fn on_finalize_rewarded_miner() -> Weight;
}

/// Maximum number of ZK-tree leaf inserts a single `on_finalize` can trigger.
///
/// `on_finalize` mints up to three rewards — transaction fees and the block
/// reward to the miner, plus the treasury portion — and each successful mint
/// records a wormhole transfer proof that inserts one leaf. Priced as three
/// independent inserts (no cross-insert storage dedup) for a conservative
/// worst case.
const MAX_LEAF_INSERTS: u64 = 3;

/// Non-Zk-tree storage measured by the benchmark, split out from the leaf-insert
/// cost so the latter can be priced at the live tree depth. Covers
/// `MiningRewards::CollectedFees` (r1 w1), `TreasuryPallet::TreasuryPortion`
/// (r1), `TreasuryPallet::TreasuryAccount` (r1), `System::Account` (r2 w2) and
/// `Wormhole::TransferCount` (r2 w2).
const BASE_READS: u64 = 7;
const BASE_WRITES: u64 = 5;

/// Weights for `pallet_mining_rewards` using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config + pallet_zk_tree::Config> WeightInfo for SubstrateWeight<T> {
	/// `on_finalize` mints up to three rewards, each recording a wormhole transfer
	/// proof whose ZK-tree leaf insert walks the tree leaf-to-root. That insert
	/// cost grows with the *current* tree depth, so it is priced from live storage
	/// (`insert_leaf_db_ops`) rather than the shallow value the benchmark measured —
	/// otherwise this mandatory hook silently under-charges as the shared tree
	/// deepens. The compute time and proof size stay at the benchmarked values; the
	/// depth-sensitive cost is the extra tree reads/writes, mirroring the runtime's
	/// per-transfer proof metering.
	fn on_finalize_rewarded_miner() -> Weight {
		// Minimum execution time: 161_000_000 picoseconds.
		let (tree_reads, tree_writes) = pallet_zk_tree::Pallet::<T>::insert_leaf_db_ops();
		Weight::from_parts(163_000_000, 8619)
			.saturating_add(T::DbWeight::get().reads(
				BASE_READS.saturating_add(MAX_LEAF_INSERTS.saturating_mul(tree_reads)),
			))
			.saturating_add(T::DbWeight::get().writes(
				BASE_WRITES.saturating_add(MAX_LEAF_INSERTS.saturating_mul(tree_writes)),
			))
	}
}

// For backwards compatibility and tests.
impl WeightInfo for () {
	/// Depth-blind fallback: the leaf inserts are priced at `MAX_TREE_DEPTH` so this
	/// can never charge less than `SubstrateWeight` at any live tree depth.
	fn on_finalize_rewarded_miner() -> Weight {
		// Minimum execution time: 161_000_000 picoseconds.
		let (tree_reads, tree_writes) =
			pallet_zk_tree::insert_leaf_db_ops_at_depth(pallet_zk_tree::MAX_TREE_DEPTH);
		Weight::from_parts(163_000_000, 8619)
			.saturating_add(RocksDbWeight::get().reads(
				BASE_READS.saturating_add(MAX_LEAF_INSERTS.saturating_mul(tree_reads)),
			))
			.saturating_add(RocksDbWeight::get().writes(
				BASE_WRITES.saturating_add(MAX_LEAF_INSERTS.saturating_mul(tree_writes)),
			))
	}
}

#[cfg(test)]
mod tests {
	use super::*;

	/// The depth-blind fallback must price its leaf inserts at `MAX_TREE_DEPTH`,
	/// so it can never charge less than the live-depth `SubstrateWeight`.
	#[test]
	fn fallback_prices_leaf_inserts_at_max_depth() {
		let (tree_reads, tree_writes) =
			pallet_zk_tree::insert_leaf_db_ops_at_depth(pallet_zk_tree::MAX_TREE_DEPTH);
		let expected = Weight::from_parts(163_000_000, 8619)
			.saturating_add(RocksDbWeight::get().reads(
				BASE_READS.saturating_add(MAX_LEAF_INSERTS.saturating_mul(tree_reads)),
			))
			.saturating_add(RocksDbWeight::get().writes(
				BASE_WRITES.saturating_add(MAX_LEAF_INSERTS.saturating_mul(tree_writes)),
			));
		assert_eq!(<() as WeightInfo>::on_finalize_rewarded_miner(), expected);
	}

	/// The mandatory hook's reserved weight must grow with tree depth — that is the
	/// whole point of pricing the leaf inserts from live depth rather than a flat
	/// benchmark constant.
	#[test]
	fn reserved_weight_grows_with_tree_depth() {
		let (shallow_r, shallow_w) = pallet_zk_tree::insert_leaf_db_ops_at_depth(1);
		let (deep_r, deep_w) =
			pallet_zk_tree::insert_leaf_db_ops_at_depth(pallet_zk_tree::MAX_TREE_DEPTH);
		assert!(deep_r > shallow_r, "leaf-insert reads must grow with depth");
		assert!(deep_w > shallow_w, "leaf-insert writes must grow with depth");
	}
}
