---
name: ubuntu dependencies
description: installs dependencies required to compile the node and runtime on ubuntu

runs:
  using: composite
  steps:
    - name: rust compilation prerequisites (ubuntu)
      if: contains(matrix.os, 'ubuntu')
      run: |
        sudo apt-get update -yqq
        sudo apt-get install -yqq --no-install-recommends \
          libclang-dev \
          protobuf-compiler
        rustup update
        rustup toolchain install ${RUSTUP_TOOLCHAIN}
        rustup target add wasm32-unknown-unknown \
          --toolchain ${RUSTUP_TOOLCHAIN}-x86_64-unknown-linux-gnu
        rustup component add rustfmt clippy rust-src \
          --toolchain ${RUSTUP_TOOLCHAIN}-x86_64-unknown-linux-gnu
        # install taplo
        curl -Ls "https://github.com/tamasfe/taplo/releases/download/0.10.0/taplo-linux-x86_64.gz" | \
        gzip -d > taplo && \
        chmod +x taplo && \
        sudo mv taplo /usr/local/bin/taplo
      shell: bash
