---
name: ubuntu dependencies
description: installs dependencies required to compile the node and runtime on ubuntu

runs:
  using: composite
  steps:
    - name: rust compilation prerequisites (ubuntu)
      run: |
        sudo apt-get update -yqq
        sudo apt-get install -yqq --no-install-recommends \
          libclang-dev \
          protobuf-compiler
        rustup update
        rustup target add wasm32-unknown-unknown
        rustup component add rustfmt clippy rust-src
      shell: bash
