use core::marker::PhantomData;
use frame_support::weights::Weight;

// Conservative placeholder weights for delegated L1 aggregation.
//
// These values are intentionally explicit but are not benchmark-generated.
// TODO: Replace them with autogenerated benchmark output before merging.
const SUBMIT_L0_CANDIDATE: Weight = Weight::from_parts(150_000_000, 0);
const REGISTER_AGGREGATOR: Weight = Weight::from_parts(25_000_000, 0);
const UPDATE_AGGREGATOR: Weight = Weight::from_parts(25_000_000, 0);
const UNREGISTER_AGGREGATOR: Weight = Weight::from_parts(25_000_000, 0);
const CLAIM_BUNDLE: Weight = Weight::from_parts(175_000_000, 0);
const SUBMIT_L1_AGGREGATE_CHEAP_REJECT: Weight = Weight::from_parts(75_000_000, 0);
const SUBMIT_L1_AGGREGATE_VALID_PROOF: Weight = Weight::from_parts(750_000_000, 0);
const TIMEOUT_BUNDLE: Weight = Weight::from_parts(75_000_000, 0);
const CHALLENGE_INVALID_L0_CANDIDATE: Weight = Weight::from_parts(600_000_000, 0);
const CHALLENGE_INVALID_L0_IN_BUNDLE: Weight = Weight::from_parts(700_000_000, 0);
const DROP_EXPIRED_CANDIDATE: Weight = Weight::from_parts(35_000_000, 0);

pub trait WeightInfo {
	fn submit_l0_candidate() -> Weight;
	fn register_aggregator() -> Weight;
	fn update_aggregator() -> Weight;
	fn unregister_aggregator() -> Weight;
	fn claim_bundle() -> Weight;
	fn timeout_bundle() -> Weight;
	fn submit_l1_aggregate_cheap_reject() -> Weight;
	fn submit_l1_aggregate_valid_proof() -> Weight;
	fn submit_l1_aggregate() -> Weight;
	fn challenge_invalid_l0_candidate() -> Weight;
	fn challenge_invalid_l0_in_bundle() -> Weight;
	fn drop_expired_candidate() -> Weight;
}

pub struct SubstrateWeight<T>(PhantomData<T>);

impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	fn submit_l0_candidate() -> Weight {
		SUBMIT_L0_CANDIDATE
	}

	fn register_aggregator() -> Weight {
		REGISTER_AGGREGATOR
	}

	fn update_aggregator() -> Weight {
		UPDATE_AGGREGATOR
	}

	fn unregister_aggregator() -> Weight {
		UNREGISTER_AGGREGATOR
	}

	fn claim_bundle() -> Weight {
		CLAIM_BUNDLE
	}

	fn timeout_bundle() -> Weight {
		TIMEOUT_BUNDLE
	}

	fn submit_l1_aggregate_cheap_reject() -> Weight {
		SUBMIT_L1_AGGREGATE_CHEAP_REJECT
	}

	fn submit_l1_aggregate_valid_proof() -> Weight {
		SUBMIT_L1_AGGREGATE_VALID_PROOF
	}

	fn submit_l1_aggregate() -> Weight {
		Self::submit_l1_aggregate_valid_proof()
	}

	fn challenge_invalid_l0_candidate() -> Weight {
		CHALLENGE_INVALID_L0_CANDIDATE
	}

	fn challenge_invalid_l0_in_bundle() -> Weight {
		CHALLENGE_INVALID_L0_IN_BUNDLE
	}

	fn drop_expired_candidate() -> Weight {
		DROP_EXPIRED_CANDIDATE
	}
}

impl WeightInfo for () {
	fn submit_l0_candidate() -> Weight {
		SUBMIT_L0_CANDIDATE
	}

	fn register_aggregator() -> Weight {
		REGISTER_AGGREGATOR
	}

	fn update_aggregator() -> Weight {
		UPDATE_AGGREGATOR
	}

	fn unregister_aggregator() -> Weight {
		UNREGISTER_AGGREGATOR
	}

	fn claim_bundle() -> Weight {
		CLAIM_BUNDLE
	}

	fn timeout_bundle() -> Weight {
		TIMEOUT_BUNDLE
	}

	fn submit_l1_aggregate_cheap_reject() -> Weight {
		SUBMIT_L1_AGGREGATE_CHEAP_REJECT
	}

	fn submit_l1_aggregate_valid_proof() -> Weight {
		SUBMIT_L1_AGGREGATE_VALID_PROOF
	}

	fn submit_l1_aggregate() -> Weight {
		Self::submit_l1_aggregate_valid_proof()
	}

	fn challenge_invalid_l0_candidate() -> Weight {
		CHALLENGE_INVALID_L0_CANDIDATE
	}

	fn challenge_invalid_l0_in_bundle() -> Weight {
		CHALLENGE_INVALID_L0_IN_BUNDLE
	}

	fn drop_expired_candidate() -> Weight {
		DROP_EXPIRED_CANDIDATE
	}
}
