image: rust:latest

compile:
  stage: build
  rules:
    - if: $CI_COMMIT_MESSAGE =~ /wip/i
      when: never
  tags: [rust, ubuntu]
  variables:
    CARGO_TERM_COLOR: always
    RUST_TOOLCHAIN: stable
    RUSTFLAGS: -Cdebug-assertions=y
  before_script:
    - apt-get update -yqq
    - apt-get install -yqq --no-install-recommends libclang-dev
    - apt-get install -yqq --no-install-recommends protobuf-compiler
    - rustup default stable
    - rustup update
    - rustup show
    - cargo --version
    - rustup target add wasm32-unknown-unknown
    - rustup component add rust-src
  script:
    - cargo build --locked --release --verbose
  after_script:
    - mv target/release/solochain-template-node ./resonance
    - sha256sum ./resonance | cut -d ' ' -f 1 | tee ./resonance.sha256
    - mv target/release/wbuild/solochain-template-runtime/solochain_template_runtime.compact.compressed.wasm ./resonance_runtime.compact.compressed.wasm
    - sha256sum ./resonance_runtime.compact.compressed.wasm | cut -d ' ' -f 1 | tee ./resonance_runtime.compact.compressed.wasm.sha256
  artifacts:
    paths:
      - resonance
      - resonance.sha256
      - resonance_runtime.compact.compressed.wasm
      - resonance_runtime.compact.compressed.wasm.sha256

testnet:
  stage: deploy
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
  tags: [fedora, infra]
  script:
    - ssh -o StrictHostKeyChecking=accept-new resonance@10.9.1.215 "echo 'gitlab infra runner says hello' > /home/resonance/hello-world.txt"
