image: rust:latest

variables:
  CARGO_TERM_COLOR: always
  RUST_TOOLCHAIN: stable

.common:
  before_script:
    - apt-get update -yqq
    - apt-get install -yqq --no-install-recommends libclang-dev
    - apt-get install -yqq --no-install-recommends protobuf-compiler
    - rustup default stable
    - rustup update
    - rustup show
    - cargo --version

clippy:
  variables:
    SKIP_WASM_BUILD: 1
  stage: .pre
  before_script:
    - !reference [.common, before_script]
    - rustup component add clippy
  script:
    - cargo clippy --all-targets --locked --workspace

test:
  variables:
    SKIP_WASM_BUILD: 1
  stage: test
  before_script:
    - !reference [.common, before_script]
  script:
    - cargo test

build:
  stage: build
  variables:
    RUSTFLAGS: -Cdebug-assertions=y
  before_script:
    - !reference [.common, before_script]
    - rustup target add wasm32-unknown-unknown --toolchain stable-x86_64-unknown-linux-gnu
    - rustup component add rust-src --toolchain stable-x86_64-unknown-linux-gnu
  script:
    - cargo build --locked --release --verbose
  after_script:
    - mv target/release/solochain-template-node ./resonance
    - sha256sum ./resonance | cut -d ' ' -f 1 | tee ./resonance.sha256
    - mv target/release/wbuild/solochain-template-runtime/solochain_template_runtime.compact.compressed.wasm ./resonance_runtime.compact.compressed.wasm
    - sha256sum ./resonance_runtime.compact.compressed.wasm | cut -d ' ' -f 1 | tee ./resonance_runtime.compact.compressed.wasm.sha256
  artifacts:
    paths:
      - resonance
      - resonance.sha256
      - resonance_runtime.compact.compressed.wasm
      - resonance_runtime.compact.compressed.wasm.sha256
