
//! Autogenerated weights for `pallet_treasury_config`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 49.1.0
//! DATE: 2026-01-12, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `coldbook.local`, CPU: `<UNKNOWN>`
//! WASM-EXECUTION: `Compiled`, CHAIN: `Some("dev")`, DB CACHE: 1024

// Executed Command:
// ./target/release/quantus-node
// benchmark
// pallet
// --chain=dev
// --pallet=pallet_treasury_config
// --extrinsic=*
// --steps=50
// --repeat=20
// --output=pallets/treasury-config/src/weights.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame_support::{traits::Get, weights::Weight};
use core::marker::PhantomData;

/// Weight functions needed for `pallet_treasury_config`.
pub trait WeightInfo {
	fn set_treasury_signatories(s: u32, ) -> Weight;
}

/// Weights for `pallet_treasury_config` using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	/// Storage: `TreasuryConfig::Signatories` (r:1 w:1)
	/// Proof: `TreasuryConfig::Signatories` (`max_values`: Some(1), `max_size`: Some(3202), added: 3697, mode: `MaxEncodedLen`)
	/// Storage: `TreasuryConfig::Threshold` (r:1 w:1)
	/// Proof: `TreasuryConfig::Threshold` (`max_values`: Some(1), `max_size`: Some(2), added: 497, mode: `MaxEncodedLen`)
	/// The range of component `s` is `[1, 100]`.
	fn set_treasury_signatories(s: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `449`
		//  Estimated: `4687`
		// Minimum execution time: 290_000_000 picoseconds.
		Weight::from_parts(226_636_905, 0)
			.saturating_add(Weight::from_parts(0, 4687))
			// Standard Error: 36_639
			.saturating_add(Weight::from_parts(4_652_600, 0).saturating_mul(s.into()))
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(2))
	}
}

// For backwards compatibility and tests.
impl WeightInfo for () {
	/// Storage: `TreasuryConfig::Signatories` (r:1 w:1)
	/// Proof: `TreasuryConfig::Signatories` (`max_values`: Some(1), `max_size`: Some(3202), added: 3697, mode: `MaxEncodedLen`)
	/// Storage: `TreasuryConfig::Threshold` (r:1 w:1)
	/// Proof: `TreasuryConfig::Threshold` (`max_values`: Some(1), `max_size`: Some(2), added: 497, mode: `MaxEncodedLen`)
	/// The range of component `s` is `[1, 100]`.
	fn set_treasury_signatories(s: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `449`
		//  Estimated: `4687`
		// Minimum execution time: 290_000_000 picoseconds.
		Weight::from_parts(226_636_905, 0)
			.saturating_add(Weight::from_parts(0, 4687))
			// Standard Error: 36_639
			.saturating_add(Weight::from_parts(4_652_600, 0).saturating_mul(s.into()))
			.saturating_add(frame_support::weights::constants::RocksDbWeight::get().reads(2))
			.saturating_add(frame_support::weights::constants::RocksDbWeight::get().writes(2))
	}
}
