//! Autogenerated weights for `pallet_dag_consensus`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 4.0.0-dev
//! DATE: 2024-01-01, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `localhost`, CPU: `<UNKNOWN>`
//! EXECUTION: Some(Wasm), WASM-EXECUTION: Compiled, CHAIN: Some("dev"), DB CACHE: 1024

// Executed Command:
// target/release/substrate
// benchmark
// pallet
// --chain=dev
// --steps=50
// --repeat=20
// --pallet=pallet_dag_consensus
// --extrinsic=*
// --execution=wasm
// --wasm-execution=compiled
// --output=./pallets/dag-consensus/src/weights.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use sp_std::marker::PhantomData;

/// Weight functions needed for pallet_dag_consensus.
pub trait WeightInfo {
	fn add_block_to_dag() -> Weight;
	fn recalculate_virtual_state() -> Weight;
}

/// Weights for pallet_dag_consensus using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	/// Storage: DagConsensus GhostdagData (r:10 w:1)
	/// Proof: DagConsensus GhostdagData (max_values: None, max_size: Some(1000), added: 10000, mode: MaxEncodedLen)
	/// Storage: DagConsensus BlockRelations (r:1 w:1)
	/// Proof: DagConsensus BlockRelations (max_values: None, max_size: Some(200), added: 200, mode: MaxEncodedLen)
	/// Storage: DagConsensus BlueWork (r:1 w:1)
	/// Proof: DagConsensus BlueWork (max_values: None, max_size: Some(32), added: 32, mode: MaxEncodedLen)
	/// Storage: DagConsensus DagTips (r:1 w:1)
	/// Proof: DagConsensus DagTips (max_values: Some(1), max_size: Some(320), added: 820, mode: MaxEncodedLen)
	/// Storage: DagConsensus VirtualState (r:1 w:1)
	/// Proof: DagConsensus VirtualState (max_values: Some(1), max_size: Some(400), added: 900, mode: MaxEncodedLen)
	fn add_block_to_dag() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `200`
		//  Estimated: `11952`
		// Minimum execution time: 50_000_000 picoseconds.
		Weight::from_parts(55_000_000, 11952)
			.saturating_add(T::DbWeight::get().reads(14_u64))
			.saturating_add(T::DbWeight::get().writes(5_u64))
	}

	/// Storage: DagConsensus VirtualState (r:1 w:1)
	/// Proof: DagConsensus VirtualState (max_values: Some(1), max_size: Some(400), added: 900, mode: MaxEncodedLen)
	/// Storage: DagConsensus DagTips (r:1 w:0)
	/// Proof: DagConsensus DagTips (max_values: Some(1), max_size: Some(320), added: 820, mode: MaxEncodedLen)
	/// Storage: DagConsensus BlueWork (r:10 w:0)
	/// Proof: DagConsensus BlueWork (max_values: None, max_size: Some(32), added: 320, mode: MaxEncodedLen)
	fn recalculate_virtual_state() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `150`
		//  Estimated: `4040`
		// Minimum execution time: 25_000_000 picoseconds.
		Weight::from_parts(30_000_000, 4040)
			.saturating_add(T::DbWeight::get().reads(12_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
}

// For backwards compatibility and tests
impl WeightInfo for () {
	/// Storage: DagConsensus GhostdagData (r:10 w:1)
	/// Proof: DagConsensus GhostdagData (max_values: None, max_size: Some(1000), added: 10000, mode: MaxEncodedLen)
	/// Storage: DagConsensus BlockRelations (r:1 w:1)
	/// Proof: DagConsensus BlockRelations (max_values: None, max_size: Some(200), added: 200, mode: MaxEncodedLen)
	/// Storage: DagConsensus BlueWork (r:1 w:1)
	/// Proof: DagConsensus BlueWork (max_values: None, max_size: Some(32), added: 32, mode: MaxEncodedLen)
	/// Storage: DagConsensus DagTips (r:1 w:1)
	/// Proof: DagConsensus DagTips (max_values: Some(1), max_size: Some(320), added: 820, mode: MaxEncodedLen)
	/// Storage: DagConsensus VirtualState (r:1 w:1)
	/// Proof: DagConsensus VirtualState (max_values: Some(1), max_size: Some(400), added: 900, mode: MaxEncodedLen)
	fn add_block_to_dag() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `200`
		//  Estimated: `11952`
		// Minimum execution time: 50_000_000 picoseconds.
		Weight::from_parts(55_000_000, 11952)
			.saturating_add(RocksDbWeight::get().reads(14_u64))
			.saturating_add(RocksDbWeight::get().writes(5_u64))
	}

	/// Storage: DagConsensus VirtualState (r:1 w:1)
	/// Proof: DagConsensus VirtualState (max_values: Some(1), max_size: Some(400), added: 900, mode: MaxEncodedLen)
	/// Storage: DagConsensus DagTips (r:1 w:0)
	/// Proof: DagConsensus DagTips (max_values: Some(1), max_size: Some(320), added: 820, mode: MaxEncodedLen)
	/// Storage: DagConsensus BlueWork (r:10 w:0)
	/// Proof: DagConsensus BlueWork (max_values: None, max_size: Some(32), added: 320, mode: MaxEncodedLen)
	fn recalculate_virtual_state() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `150`
		//  Estimated: `4040`
		// Minimum execution time: 25_000_000 picoseconds.
		Weight::from_parts(30_000_000, 4040)
			.saturating_add(RocksDbWeight::get().reads(12_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
}
