//! API module for QPoW ChainHead RPC
//! 
//! This module serves as the public API entry point for the QPoW-aware chainHead RPC
//! implementation. The actual RPC trait (`QpowChainHeadApiServer`) is generated by
//! the jsonrpsee `#[rpc(server)]` macro in the parent module.
//! 
//! # Usage
//! 
//! The generated trait is used by importing from the parent module:
//! 
//! ```ignore
//! use qpow_chain_head::{QpowChainHead, QpowChainHeadApiServer};
//! ```
//! 
//! # RPC Methods
//! 
//! The following RPC methods are exposed:
//! 
//! - `qpowChainHead_v1_follow` - Subscribe to chain updates
//! - `qpowChainHead_v1_unfollow` - Unsubscribe from chain updates
//! - `qpowChainHead_v1_body` - Request block body
//! - `qpowChainHead_v1_header` - Get block header
//! - `qpowChainHead_v1_call` - Execute runtime API call
//! - `qpowChainHead_v1_storage` - Query storage items
//! - `qpowChainHead_v1_continue` - Continue paginated operations
//! - `qpowChainHead_v1_stopOperation` - Cancel ongoing operations