[package]
authors.workspace = true
description = "Reversible transfers pallet"
edition.workspace = true
homepage.workspace = true
license = "Apache-2.0"
name = "pallet-reversible-transfers"
repository.workspace = true
version = "40.0.1"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = { features = ["derive", "max-encoded-len"], workspace = true }
frame-benchmarking = { optional = true, workspace = true }
frame-support.workspace = true
frame-system.workspace = true
log.workspace = true
pallet-balances.workspace = true
qp-scheduler.workspace = true
scale-info = { features = ["derive"], workspace = true }
sp-runtime.workspace = true

[dev-dependencies]
frame-support = { workspace = true, features = ["experimental"], default-features = true }
pallet-balances = { workspace = true, features = ["std"] }
pallet-preimage.workspace = true
pallet-scheduler.workspace = true
pallet-timestamp.workspace = true
pallet-utility.workspace = true
qp-scheduler.workspace = true
sp-core.workspace = true
sp-io.workspace = true

[features]
default = ["std"]
std = [
	"codec/std",
	"frame-benchmarking?/std",
	"frame-support/std",
	"frame-system/std",
	"log/std",
	"pallet-balances/std",
	"pallet-scheduler/std",
	"qp-scheduler/std",
	"scale-info/std",
	"sp-runtime/std",
	"sp-io/std",
	"sp-core/std",
	"pallet-utility/std",
	"pallet-timestamp/std",
	"pallet-preimage/std",
]
# Enable support for setting the existential deposit to zero.
insecure_zero_ed = []
runtime-benchmarks = [
	"frame-benchmarking",
	"frame-support/runtime-benchmarks",
	"frame-system/runtime-benchmarks",
	"pallet-balances/runtime-benchmarks",
	"sp-runtime/runtime-benchmarks",
]
try-runtime = [
	"frame-support/try-runtime",
	"frame-system/try-runtime",
	"sp-runtime/try-runtime",
]
