// This file is part of Substrate.

// Copyright (C) Parity Technologies (UK) Ltd.
// SPDX-License-Identifier: Apache-2.0

// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// 	http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.


//! Autogenerated weights for `pallet_reversible_transfers`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 53.0.0
//! DATE: 2026-06-07, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `Q-Beasts-MacBook-Air.local`, CPU: `<UNKNOWN>`
//! WASM-EXECUTION: `Compiled`, CHAIN: `None`, DB CACHE: `1024`

// Executed Command:
// ./target/release/quantus-node
// benchmark
// pallet
// --pallet=pallet_reversible_transfers
// --steps=50
// --repeat=20
// --runtime=./target/release/wbuild/quantus-runtime/quantus_runtime.wasm
// --genesis-builder=runtime
// --extrinsic=*
// --wasm-execution=compiled
// --heap-pages=4096
// --template=./.maintain/frame-weight-template.hbs
// --output=./pallets/reversible-transfers/src/weights.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]
#![allow(dead_code)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use core::marker::PhantomData;

/// Weight functions needed for `pallet_reversible_transfers`.
pub trait WeightInfo {
	fn set_high_security() -> Weight;
	fn schedule_transfer() -> Weight;
	fn schedule_asset_transfer() -> Weight;
	fn cancel() -> Weight;
	fn execute_transfer() -> Weight;
	fn recover_funds(n: u32, ) -> Weight;
}

/// Weights for `pallet_reversible_transfers` using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	/// Storage: `ReversibleTransfers::HighSecurityAccounts` (r:1 w:1)
	/// Proof: `ReversibleTransfers::HighSecurityAccounts` (`max_values`: None, `max_size`: Some(89), added: 2564, mode: `MaxEncodedLen`)
	/// Storage: `ReversibleTransfers::GuardianIndex` (r:1 w:1)
	/// Proof: `ReversibleTransfers::GuardianIndex` (`max_values`: None, `max_size`: Some(1073), added: 3548, mode: `MaxEncodedLen`)
	fn set_high_security() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `211`
		//  Estimated: `4538`
		// Minimum execution time: 11_000_000 picoseconds.
		Weight::from_parts(11_000_000, 4538)
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	/// Storage: `ReversibleTransfers::HighSecurityAccounts` (r:1 w:0)
	/// Proof: `ReversibleTransfers::HighSecurityAccounts` (`max_values`: None, `max_size`: Some(89), added: 2564, mode: `MaxEncodedLen`)
	/// Storage: `ReversibleTransfers::NextTransactionId` (r:1 w:1)
	/// Proof: `ReversibleTransfers::NextTransactionId` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `ReversibleTransfers::PendingTransfersBySender` (r:1 w:1)
	/// Proof: `ReversibleTransfers::PendingTransfersBySender` (`max_values`: None, `max_size`: Some(561), added: 3036, mode: `MaxEncodedLen`)
	/// Storage: `Scheduler::Lookup` (r:1 w:1)
	/// Proof: `Scheduler::Lookup` (`max_values`: None, `max_size`: Some(53), added: 2528, mode: `MaxEncodedLen`)
	/// Storage: `Timestamp::Now` (r:1 w:0)
	/// Proof: `Timestamp::Now` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `Scheduler::Agenda` (r:1 w:1)
	/// Proof: `Scheduler::Agenda` (`max_values`: None, `max_size`: Some(10018), added: 12493, mode: `MaxEncodedLen`)
	/// Storage: `Balances::Holds` (r:1 w:1)
	/// Proof: `Balances::Holds` (`max_values`: None, `max_size`: Some(85), added: 2560, mode: `MaxEncodedLen`)
	/// Storage: `ReversibleTransfers::PendingTransfers` (r:0 w:1)
	/// Proof: `ReversibleTransfers::PendingTransfers` (`max_values`: None, `max_size`: Some(165), added: 2640, mode: `MaxEncodedLen`)
	fn schedule_transfer() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `235`
		//  Estimated: `13483`
		// Minimum execution time: 58_000_000 picoseconds.
		Weight::from_parts(59_000_000, 13483)
			.saturating_add(T::DbWeight::get().reads(7_u64))
			.saturating_add(T::DbWeight::get().writes(6_u64))
	}
	/// Storage: `ReversibleTransfers::HighSecurityAccounts` (r:1 w:0)
	/// Proof: `ReversibleTransfers::HighSecurityAccounts` (`max_values`: None, `max_size`: Some(89), added: 2564, mode: `MaxEncodedLen`)
	/// Storage: `ReversibleTransfers::NextTransactionId` (r:1 w:1)
	/// Proof: `ReversibleTransfers::NextTransactionId` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `ReversibleTransfers::PendingTransfersBySender` (r:1 w:1)
	/// Proof: `ReversibleTransfers::PendingTransfersBySender` (`max_values`: None, `max_size`: Some(561), added: 3036, mode: `MaxEncodedLen`)
	/// Storage: `Scheduler::Lookup` (r:1 w:1)
	/// Proof: `Scheduler::Lookup` (`max_values`: None, `max_size`: Some(53), added: 2528, mode: `MaxEncodedLen`)
	/// Storage: `Timestamp::Now` (r:1 w:0)
	/// Proof: `Timestamp::Now` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `Scheduler::Agenda` (r:1 w:1)
	/// Proof: `Scheduler::Agenda` (`max_values`: None, `max_size`: Some(10018), added: 12493, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Asset` (r:1 w:1)
	/// Proof: `Assets::Asset` (`max_values`: None, `max_size`: Some(210), added: 2685, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Account` (r:1 w:1)
	/// Proof: `Assets::Account` (`max_values`: None, `max_size`: Some(134), added: 2609, mode: `MaxEncodedLen`)
	/// Storage: `AssetsHolder::BalancesOnHold` (r:1 w:1)
	/// Proof: `AssetsHolder::BalancesOnHold` (`max_values`: None, `max_size`: Some(84), added: 2559, mode: `MaxEncodedLen`)
	/// Storage: `AssetsHolder::Holds` (r:1 w:1)
	/// Proof: `AssetsHolder::Holds` (`max_values`: None, `max_size`: Some(105), added: 2580, mode: `MaxEncodedLen`)
	/// Storage: `ReversibleTransfers::PendingTransfers` (r:0 w:1)
	/// Proof: `ReversibleTransfers::PendingTransfers` (`max_values`: None, `max_size`: Some(165), added: 2640, mode: `MaxEncodedLen`)
	fn schedule_asset_transfer() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `629`
		//  Estimated: `13483`
		// Minimum execution time: 62_000_000 picoseconds.
		Weight::from_parts(64_000_000, 13483)
			.saturating_add(T::DbWeight::get().reads(10_u64))
			.saturating_add(T::DbWeight::get().writes(9_u64))
	}
	/// Storage: `ReversibleTransfers::PendingTransfers` (r:1 w:1)
	/// Proof: `ReversibleTransfers::PendingTransfers` (`max_values`: None, `max_size`: Some(165), added: 2640, mode: `MaxEncodedLen`)
	/// Storage: `ReversibleTransfers::HighSecurityAccounts` (r:1 w:0)
	/// Proof: `ReversibleTransfers::HighSecurityAccounts` (`max_values`: None, `max_size`: Some(89), added: 2564, mode: `MaxEncodedLen`)
	/// Storage: `ReversibleTransfers::PendingTransfersBySender` (r:1 w:1)
	/// Proof: `ReversibleTransfers::PendingTransfersBySender` (`max_values`: None, `max_size`: Some(561), added: 3036, mode: `MaxEncodedLen`)
	/// Storage: `Scheduler::Lookup` (r:1 w:1)
	/// Proof: `Scheduler::Lookup` (`max_values`: None, `max_size`: Some(53), added: 2528, mode: `MaxEncodedLen`)
	/// Storage: `Scheduler::Agenda` (r:1 w:1)
	/// Proof: `Scheduler::Agenda` (`max_values`: None, `max_size`: Some(10018), added: 12493, mode: `MaxEncodedLen`)
	/// Storage: `Balances::Holds` (r:1 w:1)
	/// Proof: `Balances::Holds` (`max_values`: None, `max_size`: Some(85), added: 2560, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Scheduler::Retries` (r:0 w:1)
	/// Proof: `Scheduler::Retries` (`max_values`: None, `max_size`: Some(40), added: 2515, mode: `MaxEncodedLen`)
	fn cancel() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `889`
		//  Estimated: `13483`
		// Minimum execution time: 78_000_000 picoseconds.
		Weight::from_parts(79_000_000, 13483)
			.saturating_add(T::DbWeight::get().reads(7_u64))
			.saturating_add(T::DbWeight::get().writes(7_u64))
	}
	/// Storage: `ReversibleTransfers::PendingTransfers` (r:1 w:1)
	/// Proof: `ReversibleTransfers::PendingTransfers` (`max_values`: None, `max_size`: Some(165), added: 2640, mode: `MaxEncodedLen`)
	/// Storage: `Balances::Holds` (r:1 w:1)
	/// Proof: `Balances::Holds` (`max_values`: None, `max_size`: Some(85), added: 2560, mode: `MaxEncodedLen`)
	/// Storage: `ReversibleTransfers::PendingTransfersBySender` (r:1 w:1)
	/// Proof: `ReversibleTransfers::PendingTransfersBySender` (`max_values`: None, `max_size`: Some(561), added: 3036, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Wormhole::TransferCount` (r:1 w:1)
	/// Proof: `Wormhole::TransferCount` (`max_values`: None, `max_size`: Some(56), added: 2531, mode: `MaxEncodedLen`)
	/// Storage: `ZkTree::LeafCount` (r:1 w:1)
	/// Proof: `ZkTree::LeafCount` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `ZkTree::Depth` (r:1 w:1)
	/// Proof: `ZkTree::Depth` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	/// Storage: `ZkTree::Leaves` (r:3 w:1)
	/// Proof: `ZkTree::Leaves` (`max_values`: None, `max_size`: Some(68), added: 2543, mode: `MaxEncodedLen`)
	/// Storage: `ZkTree::Root` (r:0 w:1)
	/// Proof: `ZkTree::Root` (`max_values`: Some(1), `max_size`: Some(32), added: 527, mode: `MaxEncodedLen`)
	fn execute_transfer() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `639`
		//  Estimated: `8619`
		// Minimum execution time: 105_000_000 picoseconds.
		Weight::from_parts(110_000_000, 8619)
			.saturating_add(T::DbWeight::get().reads(10_u64))
			.saturating_add(T::DbWeight::get().writes(9_u64))
	}
	/// Storage: `ReversibleTransfers::HighSecurityAccounts` (r:1 w:0)
	/// Proof: `ReversibleTransfers::HighSecurityAccounts` (`max_values`: None, `max_size`: Some(89), added: 2564, mode: `MaxEncodedLen`)
	/// Storage: `ReversibleTransfers::PendingTransfersBySender` (r:1 w:1)
	/// Proof: `ReversibleTransfers::PendingTransfersBySender` (`max_values`: None, `max_size`: Some(561), added: 3036, mode: `MaxEncodedLen`)
	/// Storage: `ReversibleTransfers::PendingTransfers` (r:16 w:16)
	/// Proof: `ReversibleTransfers::PendingTransfers` (`max_values`: None, `max_size`: Some(165), added: 2640, mode: `MaxEncodedLen`)
	/// Storage: `Balances::Holds` (r:1 w:1)
	/// Proof: `Balances::Holds` (`max_values`: None, `max_size`: Some(85), added: 2560, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Scheduler::Lookup` (r:16 w:16)
	/// Proof: `Scheduler::Lookup` (`max_values`: None, `max_size`: Some(53), added: 2528, mode: `MaxEncodedLen`)
	/// Storage: `Scheduler::Agenda` (r:2 w:2)
	/// Proof: `Scheduler::Agenda` (`max_values`: None, `max_size`: Some(10018), added: 12493, mode: `MaxEncodedLen`)
	/// Storage: `Scheduler::Retries` (r:0 w:16)
	/// Proof: `Scheduler::Retries` (`max_values`: None, `max_size`: Some(40), added: 2515, mode: `MaxEncodedLen`)
	/// The range of component `n` is `[0, 16]`.
	fn recover_funds(n: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `522 + n * (364 ±0)`
		//  Estimated: `9482 + n * (2640 ±32)`
		// Minimum execution time: 52_000_000 picoseconds.
		Weight::from_parts(55_250_404, 9482)
			// Standard Error: 70_515
			.saturating_add(Weight::from_parts(56_328_935, 0).saturating_mul(n.into()))
			.saturating_add(T::DbWeight::get().reads(4_u64))
			.saturating_add(T::DbWeight::get().reads((2_u64).saturating_mul(n.into())))
			.saturating_add(T::DbWeight::get().writes(3_u64))
			.saturating_add(T::DbWeight::get().writes((3_u64).saturating_mul(n.into())))
			.saturating_add(Weight::from_parts(0, 2640).saturating_mul(n.into()))
	}
}

// For backwards compatibility and tests.
impl WeightInfo for () {
	/// Storage: `ReversibleTransfers::HighSecurityAccounts` (r:1 w:1)
	/// Proof: `ReversibleTransfers::HighSecurityAccounts` (`max_values`: None, `max_size`: Some(89), added: 2564, mode: `MaxEncodedLen`)
	/// Storage: `ReversibleTransfers::GuardianIndex` (r:1 w:1)
	/// Proof: `ReversibleTransfers::GuardianIndex` (`max_values`: None, `max_size`: Some(1073), added: 3548, mode: `MaxEncodedLen`)
	fn set_high_security() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `211`
		//  Estimated: `4538`
		// Minimum execution time: 11_000_000 picoseconds.
		Weight::from_parts(11_000_000, 4538)
			.saturating_add(RocksDbWeight::get().reads(2_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
	/// Storage: `ReversibleTransfers::HighSecurityAccounts` (r:1 w:0)
	/// Proof: `ReversibleTransfers::HighSecurityAccounts` (`max_values`: None, `max_size`: Some(89), added: 2564, mode: `MaxEncodedLen`)
	/// Storage: `ReversibleTransfers::NextTransactionId` (r:1 w:1)
	/// Proof: `ReversibleTransfers::NextTransactionId` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `ReversibleTransfers::PendingTransfersBySender` (r:1 w:1)
	/// Proof: `ReversibleTransfers::PendingTransfersBySender` (`max_values`: None, `max_size`: Some(561), added: 3036, mode: `MaxEncodedLen`)
	/// Storage: `Scheduler::Lookup` (r:1 w:1)
	/// Proof: `Scheduler::Lookup` (`max_values`: None, `max_size`: Some(53), added: 2528, mode: `MaxEncodedLen`)
	/// Storage: `Timestamp::Now` (r:1 w:0)
	/// Proof: `Timestamp::Now` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `Scheduler::Agenda` (r:1 w:1)
	/// Proof: `Scheduler::Agenda` (`max_values`: None, `max_size`: Some(10018), added: 12493, mode: `MaxEncodedLen`)
	/// Storage: `Balances::Holds` (r:1 w:1)
	/// Proof: `Balances::Holds` (`max_values`: None, `max_size`: Some(85), added: 2560, mode: `MaxEncodedLen`)
	/// Storage: `ReversibleTransfers::PendingTransfers` (r:0 w:1)
	/// Proof: `ReversibleTransfers::PendingTransfers` (`max_values`: None, `max_size`: Some(165), added: 2640, mode: `MaxEncodedLen`)
	fn schedule_transfer() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `235`
		//  Estimated: `13483`
		// Minimum execution time: 58_000_000 picoseconds.
		Weight::from_parts(59_000_000, 13483)
			.saturating_add(RocksDbWeight::get().reads(7_u64))
			.saturating_add(RocksDbWeight::get().writes(6_u64))
	}
	/// Storage: `ReversibleTransfers::HighSecurityAccounts` (r:1 w:0)
	/// Proof: `ReversibleTransfers::HighSecurityAccounts` (`max_values`: None, `max_size`: Some(89), added: 2564, mode: `MaxEncodedLen`)
	/// Storage: `ReversibleTransfers::NextTransactionId` (r:1 w:1)
	/// Proof: `ReversibleTransfers::NextTransactionId` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `ReversibleTransfers::PendingTransfersBySender` (r:1 w:1)
	/// Proof: `ReversibleTransfers::PendingTransfersBySender` (`max_values`: None, `max_size`: Some(561), added: 3036, mode: `MaxEncodedLen`)
	/// Storage: `Scheduler::Lookup` (r:1 w:1)
	/// Proof: `Scheduler::Lookup` (`max_values`: None, `max_size`: Some(53), added: 2528, mode: `MaxEncodedLen`)
	/// Storage: `Timestamp::Now` (r:1 w:0)
	/// Proof: `Timestamp::Now` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `Scheduler::Agenda` (r:1 w:1)
	/// Proof: `Scheduler::Agenda` (`max_values`: None, `max_size`: Some(10018), added: 12493, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Asset` (r:1 w:1)
	/// Proof: `Assets::Asset` (`max_values`: None, `max_size`: Some(210), added: 2685, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Account` (r:1 w:1)
	/// Proof: `Assets::Account` (`max_values`: None, `max_size`: Some(134), added: 2609, mode: `MaxEncodedLen`)
	/// Storage: `AssetsHolder::BalancesOnHold` (r:1 w:1)
	/// Proof: `AssetsHolder::BalancesOnHold` (`max_values`: None, `max_size`: Some(84), added: 2559, mode: `MaxEncodedLen`)
	/// Storage: `AssetsHolder::Holds` (r:1 w:1)
	/// Proof: `AssetsHolder::Holds` (`max_values`: None, `max_size`: Some(105), added: 2580, mode: `MaxEncodedLen`)
	/// Storage: `ReversibleTransfers::PendingTransfers` (r:0 w:1)
	/// Proof: `ReversibleTransfers::PendingTransfers` (`max_values`: None, `max_size`: Some(165), added: 2640, mode: `MaxEncodedLen`)
	fn schedule_asset_transfer() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `629`
		//  Estimated: `13483`
		// Minimum execution time: 62_000_000 picoseconds.
		Weight::from_parts(64_000_000, 13483)
			.saturating_add(RocksDbWeight::get().reads(10_u64))
			.saturating_add(RocksDbWeight::get().writes(9_u64))
	}
	/// Storage: `ReversibleTransfers::PendingTransfers` (r:1 w:1)
	/// Proof: `ReversibleTransfers::PendingTransfers` (`max_values`: None, `max_size`: Some(165), added: 2640, mode: `MaxEncodedLen`)
	/// Storage: `ReversibleTransfers::HighSecurityAccounts` (r:1 w:0)
	/// Proof: `ReversibleTransfers::HighSecurityAccounts` (`max_values`: None, `max_size`: Some(89), added: 2564, mode: `MaxEncodedLen`)
	/// Storage: `ReversibleTransfers::PendingTransfersBySender` (r:1 w:1)
	/// Proof: `ReversibleTransfers::PendingTransfersBySender` (`max_values`: None, `max_size`: Some(561), added: 3036, mode: `MaxEncodedLen`)
	/// Storage: `Scheduler::Lookup` (r:1 w:1)
	/// Proof: `Scheduler::Lookup` (`max_values`: None, `max_size`: Some(53), added: 2528, mode: `MaxEncodedLen`)
	/// Storage: `Scheduler::Agenda` (r:1 w:1)
	/// Proof: `Scheduler::Agenda` (`max_values`: None, `max_size`: Some(10018), added: 12493, mode: `MaxEncodedLen`)
	/// Storage: `Balances::Holds` (r:1 w:1)
	/// Proof: `Balances::Holds` (`max_values`: None, `max_size`: Some(85), added: 2560, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Scheduler::Retries` (r:0 w:1)
	/// Proof: `Scheduler::Retries` (`max_values`: None, `max_size`: Some(40), added: 2515, mode: `MaxEncodedLen`)
	fn cancel() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `889`
		//  Estimated: `13483`
		// Minimum execution time: 78_000_000 picoseconds.
		Weight::from_parts(79_000_000, 13483)
			.saturating_add(RocksDbWeight::get().reads(7_u64))
			.saturating_add(RocksDbWeight::get().writes(7_u64))
	}
	/// Storage: `ReversibleTransfers::PendingTransfers` (r:1 w:1)
	/// Proof: `ReversibleTransfers::PendingTransfers` (`max_values`: None, `max_size`: Some(165), added: 2640, mode: `MaxEncodedLen`)
	/// Storage: `Balances::Holds` (r:1 w:1)
	/// Proof: `Balances::Holds` (`max_values`: None, `max_size`: Some(85), added: 2560, mode: `MaxEncodedLen`)
	/// Storage: `ReversibleTransfers::PendingTransfersBySender` (r:1 w:1)
	/// Proof: `ReversibleTransfers::PendingTransfersBySender` (`max_values`: None, `max_size`: Some(561), added: 3036, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Wormhole::TransferCount` (r:1 w:1)
	/// Proof: `Wormhole::TransferCount` (`max_values`: None, `max_size`: Some(56), added: 2531, mode: `MaxEncodedLen`)
	/// Storage: `ZkTree::LeafCount` (r:1 w:1)
	/// Proof: `ZkTree::LeafCount` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `ZkTree::Depth` (r:1 w:1)
	/// Proof: `ZkTree::Depth` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	/// Storage: `ZkTree::Leaves` (r:3 w:1)
	/// Proof: `ZkTree::Leaves` (`max_values`: None, `max_size`: Some(68), added: 2543, mode: `MaxEncodedLen`)
	/// Storage: `ZkTree::Root` (r:0 w:1)
	/// Proof: `ZkTree::Root` (`max_values`: Some(1), `max_size`: Some(32), added: 527, mode: `MaxEncodedLen`)
	fn execute_transfer() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `639`
		//  Estimated: `8619`
		// Minimum execution time: 105_000_000 picoseconds.
		Weight::from_parts(110_000_000, 8619)
			.saturating_add(RocksDbWeight::get().reads(10_u64))
			.saturating_add(RocksDbWeight::get().writes(9_u64))
	}
	/// Storage: `ReversibleTransfers::HighSecurityAccounts` (r:1 w:0)
	/// Proof: `ReversibleTransfers::HighSecurityAccounts` (`max_values`: None, `max_size`: Some(89), added: 2564, mode: `MaxEncodedLen`)
	/// Storage: `ReversibleTransfers::PendingTransfersBySender` (r:1 w:1)
	/// Proof: `ReversibleTransfers::PendingTransfersBySender` (`max_values`: None, `max_size`: Some(561), added: 3036, mode: `MaxEncodedLen`)
	/// Storage: `ReversibleTransfers::PendingTransfers` (r:16 w:16)
	/// Proof: `ReversibleTransfers::PendingTransfers` (`max_values`: None, `max_size`: Some(165), added: 2640, mode: `MaxEncodedLen`)
	/// Storage: `Balances::Holds` (r:1 w:1)
	/// Proof: `Balances::Holds` (`max_values`: None, `max_size`: Some(85), added: 2560, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Scheduler::Lookup` (r:16 w:16)
	/// Proof: `Scheduler::Lookup` (`max_values`: None, `max_size`: Some(53), added: 2528, mode: `MaxEncodedLen`)
	/// Storage: `Scheduler::Agenda` (r:2 w:2)
	/// Proof: `Scheduler::Agenda` (`max_values`: None, `max_size`: Some(10018), added: 12493, mode: `MaxEncodedLen`)
	/// Storage: `Scheduler::Retries` (r:0 w:16)
	/// Proof: `Scheduler::Retries` (`max_values`: None, `max_size`: Some(40), added: 2515, mode: `MaxEncodedLen`)
	/// The range of component `n` is `[0, 16]`.
	fn recover_funds(n: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `522 + n * (364 ±0)`
		//  Estimated: `9482 + n * (2640 ±32)`
		// Minimum execution time: 52_000_000 picoseconds.
		Weight::from_parts(55_250_404, 9482)
			// Standard Error: 70_515
			.saturating_add(Weight::from_parts(56_328_935, 0).saturating_mul(n.into()))
			.saturating_add(RocksDbWeight::get().reads(4_u64))
			.saturating_add(RocksDbWeight::get().reads((2_u64).saturating_mul(n.into())))
			.saturating_add(RocksDbWeight::get().writes(3_u64))
			.saturating_add(RocksDbWeight::get().writes((3_u64).saturating_mul(n.into())))
			.saturating_add(Weight::from_parts(0, 2640).saturating_mul(n.into()))
	}
}
