//! Build script for pallet-wormhole.
//!
//! Generates circuit binaries (leaf + one aggregated verifier per supported
//! `num_leaf_proofs`) at build time. Binaries are embedded into the runtime
//! via `include_bytes!` in `src/lib.rs` (through the generated
//! `verifiers_manifest.rs` file in `OUT_DIR`).
//!
//! Supported aggregation sizes are read from the environment:
//!
//!   - `QP_NUM_LEAF_PROOFS_LIST=2,16` (preferred): comma-separated list.
//!   - `QP_NUM_LEAF_PROOFS=N` (legacy): single value, treated as `[N]`.
//!
//! Default if neither is set: `2,16` (low-memory mobile + max-privacy desktop).

use std::{
	env, fs,
	path::{Path, PathBuf},
	time::Instant,
};

const DEFAULT_SUPPORTED: &str = "2,16";

fn poseidon_hex(data: &[u8]) -> String {
	let hash = qp_poseidon_core::hash_bytes(data);
	hex::encode(&hash[..16])
}

fn print_bin_hash(dir: &Path, filename: &str) {
	let path = dir.join(filename);
	if let Ok(data) = fs::read(&path) {
		println!(
			"cargo:warning=  {}: {} bytes, hash: {}",
			filename,
			data.len(),
			poseidon_hex(&data)
		);
	}
}

fn parse_supported_list() -> Vec<usize> {
	if let Ok(list) = env::var("QP_NUM_LEAF_PROOFS_LIST") {
		return list
			.split(',')
			.map(|s| s.trim())
			.filter(|s| !s.is_empty())
			.map(|s| {
				s.parse::<usize>()
					.expect("QP_NUM_LEAF_PROOFS_LIST entries must be positive integers")
			})
			.collect();
	}
	if let Ok(single) = env::var("QP_NUM_LEAF_PROOFS") {
		return vec![single
			.parse()
			.expect("QP_NUM_LEAF_PROOFS must be a positive integer")];
	}
	DEFAULT_SUPPORTED
		.split(',')
		.map(|s| s.parse::<usize>().expect("default supported list parse"))
		.collect()
}

fn rename_agg_outputs(out_path: &Path, n: usize) {
	for stem in ["aggregated_common", "aggregated_verifier"] {
		let src = out_path.join(format!("{}.bin", stem));
		let dst = out_path.join(format!("{}_{}.bin", stem, n));
		fs::rename(&src, &dst).unwrap_or_else(|e| {
			panic!("failed to rename {:?} -> {:?}: {}", src, dst, e);
		});
		print_bin_hash(out_path, &format!("{}_{}.bin", stem, n));
	}
}

fn write_manifest(out_path: &Path, supported: &[usize]) {
	let mut buf = String::new();
	buf.push_str("// Auto-generated by build.rs. Do not edit.\n\n");
	buf.push_str("pub const SUPPORTED_NUM_LEAF_PROOFS: &[u32] = &[");
	for (i, n) in supported.iter().enumerate() {
		if i > 0 {
			buf.push_str(", ");
		}
		buf.push_str(&n.to_string());
	}
	buf.push_str("];\n\n");

	buf.push_str(
		"pub fn load_supported_verifiers(\n\
		 ) -> alloc::vec::Vec<(u32, qp_wormhole_verifier::WormholeVerifier)> {\n\
		 \x20   let mut out: alloc::vec::Vec<(u32, qp_wormhole_verifier::WormholeVerifier)> =\n\
		 \x20       alloc::vec::Vec::new();\n",
	);
	for n in supported {
		buf.push_str(&format!(
			"    if let Ok(v) = qp_wormhole_verifier::WormholeVerifier::new_from_bytes(\n\
			 \x20       include_bytes!(\"aggregated_verifier_{n}.bin\"),\n\
			 \x20       include_bytes!(\"aggregated_common_{n}.bin\"),\n\
			 \x20   ) {{\n\
			 \x20       out.push(({n}u32, v));\n\
			 \x20   }}\n",
			n = n
		));
	}
	buf.push_str("    out\n}\n");

	fs::write(out_path.join("verifiers_manifest.rs"), buf)
		.expect("failed to write verifiers_manifest.rs");
}

fn main() {
	let out_dir = env::var("OUT_DIR").expect("OUT_DIR not set");
	let out_path = PathBuf::from(&out_dir);

	let supported = parse_supported_list();
	assert!(
		!supported.is_empty(),
		"at least one supported num_leaf_proofs is required"
	);

	println!(
		"cargo:warning=[pallet-wormhole] generating ZK circuit binaries for num_leaf_proofs={:?}...",
		supported
	);

	let start = Instant::now();

	qp_wormhole_circuit_builder::generate_circuit_binaries(&out_path, false)
		.expect("failed to generate leaf circuit binaries");

	for n in &supported {
		qp_wormhole_aggregator::layer0::circuit::build::generate_layer0_circuit_binaries(
			&out_path, *n, false,
		)
		.unwrap_or_else(|e| panic!("failed to build aggregation circuit for N={}: {}", n, e));
		rename_agg_outputs(&out_path, *n);
	}

	println!(
		"cargo:warning=[pallet-wormhole] ZK circuit binaries generated in {:.2}s",
		start.elapsed().as_secs_f64()
	);

	print_bin_hash(&out_path, "common.bin");
	print_bin_hash(&out_path, "verifier.bin");
	print_bin_hash(&out_path, "dummy_proof.bin");

	write_manifest(&out_path, &supported);

	println!("cargo:rerun-if-env-changed=QP_NUM_LEAF_PROOFS");
	println!("cargo:rerun-if-env-changed=QP_NUM_LEAF_PROOFS_LIST");
}
