---
name: macos dependencies
description: installs dependencies required to compile the node and runtime on macos

runs:
  using: composite
  steps:
    - name: rust compilation prerequisites (macos)
      run: |
        brew install protobuf
        curl https://sh.rustup.rs -sSf | sh -s -- -y
        rustup update
        rustup target add wasm32-unknown-unknown
        rustup component add rustfmt clippy rust-src
      shell: sh
