// This file is part of Substrate.

// Copyright (C) Parity Technologies (UK) Ltd.
// SPDX-License-Identifier: Apache-2.0

// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// 	http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.


//! Autogenerated weights for `pallet_wormhole`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 53.0.0
//! DATE: 2026-04-03, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `Yuvis-MacBook-Air.local`, CPU: `<UNKNOWN>`
//! WASM-EXECUTION: `Compiled`, CHAIN: `None`, DB CACHE: `1024`

// Executed Command:
// ./target/release/quantus-node
// benchmark
// pallet
// --pallet
// pallet-wormhole
// --extrinsic
// *
// --steps
// 50
// --repeat
// 20
// --output
// ./pallets/wormhole/src/weights.rs
// --template
// ./.maintain/frame-weight-template.hbs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]
#![allow(dead_code)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use core::marker::PhantomData;

/// Weight functions needed for `pallet_wormhole`.
pub trait WeightInfo {
	fn pre_validate_proof() -> Weight;
	fn verify_aggregated_proof() -> Weight;
}

/// Weights for `pallet_wormhole` using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	/// Storage: `System::BlockHash` (r:1 w:0)
	/// Proof: `System::BlockHash` (`max_values`: None, `max_size`: Some(44), added: 2519, mode: `MaxEncodedLen`)
	/// Storage: `Wormhole::UsedNullifiers` (r:32 w:0)
	/// Proof: `Wormhole::UsedNullifiers` (`max_values`: None, `max_size`: Some(49), added: 2524, mode: `MaxEncodedLen`)
	fn pre_validate_proof() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `81758`
		// Minimum execution time: 4_045_000_000 picoseconds.
		Weight::from_parts(5_143_000_000, 81758)
			.saturating_add(T::DbWeight::get().reads(33_u64))
	}
	/// Full aggregated proof verification including ZK verification and state updates.
	/// 
	/// Storage operations (worst case with 32 nullifiers and 32 exit accounts):
	/// - `System::BlockHash` (r:1 w:0) - block hash lookup in pre_validate
	/// - `Wormhole::UsedNullifiers` (r:32 w:32) - check in pre_validate, mark in dispatch
	/// - `System::Digest` (r:1 w:0) - get block author for miner fee
	/// - `System::Account` (r:1 w:1) - miner fee recipient
	/// - `Currency::TotalIssuance` (r:1 w:1) - burn fee portion
	/// - `System::Account` (r:32 w:32) - mint to exit accounts
	/// - `Wormhole::TransferCount` (r:32 w:32) - read/update per transfer
	/// - `Wormhole::TransferProof` (r:0 w:32) - store transfer proofs
	/// 
	/// Total: reads=100, writes=130
	fn verify_aggregated_proof() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `200000`
		// Minimum execution time: 38_843_000_000 picoseconds (ZK verification only).
		// Adding pre_validate_proof time (~5ms) for total ~45ms
		Weight::from_parts(45_155_000_000, 200000)
			.saturating_add(T::DbWeight::get().reads(100_u64))
			.saturating_add(T::DbWeight::get().writes(130_u64))
	}
}

// For backwards compatibility and tests.
impl WeightInfo for () {
	/// Storage: `System::BlockHash` (r:1 w:0)
	/// Proof: `System::BlockHash` (`max_values`: None, `max_size`: Some(44), added: 2519, mode: `MaxEncodedLen`)
	/// Storage: `Wormhole::UsedNullifiers` (r:32 w:0)
	/// Proof: `Wormhole::UsedNullifiers` (`max_values`: None, `max_size`: Some(49), added: 2524, mode: `MaxEncodedLen`)
	fn pre_validate_proof() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `81758`
		// Minimum execution time: 4_045_000_000 picoseconds.
		Weight::from_parts(5_143_000_000, 81758)
			.saturating_add(RocksDbWeight::get().reads(33_u64))
	}
	/// Full aggregated proof verification including ZK verification and state updates.
	/// Total: reads=100, writes=130 (see SubstrateWeight impl for breakdown)
	fn verify_aggregated_proof() -> Weight {
		// Minimum execution time: 38_843_000_000 picoseconds (ZK verification only).
		// Adding pre_validate_proof time (~5ms) for total ~45ms
		Weight::from_parts(45_155_000_000, 200000)
			.saturating_add(RocksDbWeight::get().reads(100_u64))
			.saturating_add(RocksDbWeight::get().writes(130_u64))
	}
}
