// This file is part of Substrate.

// Copyright (C) Parity Technologies (UK) Ltd.
// SPDX-License-Identifier: Apache-2.0

// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// 	http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//! Autogenerated weights for `pallet_wormhole`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 53.0.0
//! DATE: 2026-06-07, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `Q-Beasts-MacBook-Air.local`, CPU: `<UNKNOWN>`
//! WASM-EXECUTION: `Compiled`, CHAIN: `None`, DB CACHE: `1024`
//!
//! Note: the `verify_*_batch` storage tails below are hand-augmented. Keep the
//! scaling logic when regenerating from benchmarks (ZK verify time only).

// Executed Command:
// ./target/release/quantus-node
// benchmark
// pallet
// --pallet=pallet-wormhole
// --steps=50
// --repeat=20
// --runtime=./target/release/wbuild/quantus-runtime/quantus_runtime.wasm
// --genesis-builder=runtime
// --extrinsic=*
// --wasm-execution=compiled
// --heap-pages=4096
// --template=./.maintain/frame-weight-template.hbs
// --output=./pallets/wormhole/src/weights.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]
#![allow(dead_code)]

use crate::circuit_config;
use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use core::marker::PhantomData;

/// Weight functions needed for `pallet_wormhole`.
pub trait WeightInfo {
	fn pre_validate_proof() -> Weight;
	fn verify_private_batch() -> Weight;
	fn verify_public_batch() -> Weight;
}

/// Historical hand-augmentation calibrated for a private-batch of 16 leaves
/// (2 exit slots/leaf → 32 exit mints). See `verify_private_batch` docs.
const STORAGE_CALIBRATION_EXITS: u64 = 32;
const STORAGE_CALIBRATION_READS: u64 = 200;
const STORAGE_CALIBRATION_WRITES: u64 = 170;
const STORAGE_CALIBRATION_PROOF_SIZE: u64 = 200_000;

/// Each leaf proof contributes up to two exit slots (spend + change).
const EXITS_PER_LEAF: u64 = 2;

/// Worst-case exit slots for one private-batch proof.
fn private_batch_max_exits() -> u64 {
	EXITS_PER_LEAF.saturating_mul(circuit_config::NUM_LEAF_PROOFS as u64)
}

/// Worst-case exit slots for one public-batch proof (all inner segments full).
fn public_batch_max_exits() -> u64 {
	private_batch_max_exits()
		.saturating_mul(circuit_config::NUM_PRIVATE_BATCH_PROOFS as u64)
}

/// Scale the calibrated storage tail to `exits` exit mints.
///
/// Adds one extra account read/write for the public-batch aggregator rebate when
/// `include_aggregator` is set.
fn storage_tail(exits: u64, include_aggregator: bool) -> (u64, u64, u64) {
	let reads = STORAGE_CALIBRATION_READS
		.saturating_mul(exits)
		.saturating_div(STORAGE_CALIBRATION_EXITS)
		.max(1);
	let writes = STORAGE_CALIBRATION_WRITES
		.saturating_mul(exits)
		.saturating_div(STORAGE_CALIBRATION_EXITS)
		.max(1);
	let proof_size = STORAGE_CALIBRATION_PROOF_SIZE
		.saturating_mul(exits)
		.saturating_div(STORAGE_CALIBRATION_EXITS)
		.max(1);
	if include_aggregator {
		(reads.saturating_add(1), writes.saturating_add(1), proof_size)
	} else {
		(reads, writes, proof_size)
	}
}

/// Weights for `pallet_wormhole` using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	/// Storage: `System::BlockHash` (r:1 w:0)
	/// Proof: `System::BlockHash` (`max_values`: None, `max_size`: Some(44), added: 2519, mode: `MaxEncodedLen`)
	/// Storage: `Wormhole::UsedNullifiers` (r:32 w:0)
	/// Proof: `Wormhole::UsedNullifiers` (`max_values`: None, `max_size`: Some(49), added: 2524, mode: `MaxEncodedLen`)
	fn pre_validate_proof() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1846`
		//  Estimated: `81758`
		// Minimum execution time: 650_000_000 picoseconds.
		Weight::from_parts(685_000_000, 81758)
			.saturating_add(T::DbWeight::get().reads(33_u64))
	}
	/// Full private-batch proof verification: ZK verification plus the data-dependent state
	/// updates that the `verify_private_batch` benchmark intentionally excludes (it only
	/// measures the ZK verify). Storage is scaled from a calibration of 32 exit mints
	/// (2 · 16 leaves) to `2 · NUM_LEAF_PROOFS`:
	/// - `System::BlockHash` (r:1) + `Wormhole::UsedNullifiers` (r:N w:N)
	/// - `System::Digest` (r:1), `Balances::TotalIssuance` (r:1 w:1)
	/// - `System::Account` (r:E+1 w:E+1) - exit mints + miner fee
	/// - `Wormhole::TransferCount` (r:E w:E)
	/// - `ZkTree` Leaves/Nodes/LeafCount/Depth/Root via `record_transfer`
	/// Keep this augmentation when regenerating.
	fn verify_private_batch() -> Weight {
		let (reads, writes, proof_size) = storage_tail(private_batch_max_exits(), false);
		// Minimum execution time: 15_336_000_000 picoseconds (ZK verification only).
		// Adding deserialization (~0.7ms) for total compute ~16.7ms.
		Weight::from_parts(16_661_000_000, proof_size)
			.saturating_add(T::DbWeight::get().reads(reads))
			.saturating_add(T::DbWeight::get().writes(writes))
	}
	/// Public-batch ZK verification is heavier than private-batch (recursively verifies
	/// N inner private-batch proofs). Storage scales with every exit slot across all
	/// inner segments: `2 · NUM_LEAF_PROOFS · NUM_PRIVATE_BATCH_PROOFS`, plus one
	/// account touch for the aggregator fee rebate.
	fn verify_public_batch() -> Weight {
		let (reads, writes, proof_size) = storage_tail(public_batch_max_exits(), true);
		Weight::from_parts(25_000_000_000, proof_size)
			.saturating_add(T::DbWeight::get().reads(reads))
			.saturating_add(T::DbWeight::get().writes(writes))
	}
}

// For backwards compatibility and tests.
impl WeightInfo for () {
	/// Storage: `System::BlockHash` (r:1 w:0)
	/// Proof: `System::BlockHash` (`max_values`: None, `max_size`: Some(44), added: 2519, mode: `MaxEncodedLen`)
	/// Storage: `Wormhole::UsedNullifiers` (r:32 w:0)
	/// Proof: `Wormhole::UsedNullifiers` (`max_values`: None, `max_size`: Some(49), added: 2524, mode: `MaxEncodedLen`)
	fn pre_validate_proof() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1846`
		//  Estimated: `81758`
		// Minimum execution time: 650_000_000 picoseconds.
		Weight::from_parts(685_000_000, 81758)
			.saturating_add(RocksDbWeight::get().reads(33_u64))
	}
	/// Full private-batch proof verification: ZK verification plus the data-dependent state
	/// updates that the benchmark excludes. Storage scaled to `2 · NUM_LEAF_PROOFS` exits
	/// from a 32-exit calibration. Keep this augmentation when regenerating.
	fn verify_private_batch() -> Weight {
		let (reads, writes, proof_size) = storage_tail(private_batch_max_exits(), false);
		// Minimum execution time: 15_336_000_000 picoseconds (ZK verification only).
		// Adding deserialization (~0.7ms) for total compute ~16.7ms.
		Weight::from_parts(16_661_000_000, proof_size)
			.saturating_add(RocksDbWeight::get().reads(reads))
			.saturating_add(RocksDbWeight::get().writes(writes))
	}
	fn verify_public_batch() -> Weight {
		let (reads, writes, proof_size) = storage_tail(public_batch_max_exits(), true);
		Weight::from_parts(25_000_000_000, proof_size)
			.saturating_add(RocksDbWeight::get().reads(reads))
			.saturating_add(RocksDbWeight::get().writes(writes))
	}
}

#[cfg(test)]
mod tests {
	use super::*;

	#[test]
	fn public_batch_storage_covers_all_inner_segments() {
		assert_eq!(
			public_batch_max_exits(),
			private_batch_max_exits()
				.saturating_mul(circuit_config::NUM_PRIVATE_BATCH_PROOFS as u64)
		);

		let (priv_r, priv_w, _) = storage_tail(private_batch_max_exits(), false);
		let (pub_r, pub_w, _) = storage_tail(public_batch_max_exits(), true);

		// Public must charge strictly more DB weight than a single private batch
		// whenever more than one inner segment is configured.
		if circuit_config::NUM_PRIVATE_BATCH_PROOFS > 1 {
			assert!(pub_r > priv_r);
			assert!(pub_w > priv_w);
		}
	}
}
