use crate::scheme_macro::define_dilithium_scheme;
use codec::{Decode, DecodeWithMemTracking, Encode, MaxEncodedLen};
use scale_info::TypeInfo;
use sp_core::{
	crypto::{PublicBytes, SignatureBytes},
	RuntimeDebug,
};

/// Resonance Crypto Types
///
/// Implementing the Dilithium cryptographic schemes for post quantum security:
/// ML-DSA-87 and ML-DSA-65.
///
/// Modeled after the Substrate MultiSignature and Signature types such as sr25519.
///
/// For trait implementations shared by all schemes see traits.rs; per-scheme
/// implementations are generated by `define_dilithium_scheme!`.

/// Wrapper around Substrate's PublicBytes to provide Dilithium-specific implementations
///
/// This wrapper enables the implementation of required traits for Dilithium public keys
/// while maintaining compatibility with Substrate's crypto infrastructure.
#[derive(
	Clone,
	Eq,
	PartialEq,
	Hash,
	Encode,
	Decode,
	TypeInfo,
	MaxEncodedLen,
	Ord,
	PartialOrd,
	DecodeWithMemTracking,
)]
pub struct WrappedPublicBytes<const N: usize, SubTag>(pub PublicBytes<N, SubTag>);

/// Wrapper around Substrate's SignatureBytes to provide Dilithium-specific implementations
///
/// This wrapper enables the implementation of required traits for Dilithium signatures
/// while maintaining compatibility with Substrate's crypto infrastructure.
#[derive(
	Clone,
	Eq,
	PartialEq,
	Hash,
	Encode,
	Decode,
	TypeInfo,
	MaxEncodedLen,
	Ord,
	PartialOrd,
	DecodeWithMemTracking,
)]
pub struct WrappedSignatureBytes<const N: usize, SubTag>(pub SignatureBytes<N, SubTag>);

/// Dilithium signature scheme - drop-in replacement for MultiSignature
///
/// Supports ML-DSA-87 (`Dilithium`) and ML-DSA-65 (`Dilithium65`). New variants
/// must only be appended: existing variant indices are part of the extrinsic
/// wire format.
#[derive(
	Eq,
	PartialEq,
	Clone,
	Encode,
	Decode,
	MaxEncodedLen,
	RuntimeDebug,
	TypeInfo,
	DecodeWithMemTracking,
)]
pub enum DilithiumSignatureScheme {
	Dilithium(DilithiumSignatureWithPublic),
	Dilithium65(Dilithium65SignatureWithPublic),
}

/// Dilithium signer - replacement for MultiSigner
///
/// Identifies the signer of a transaction using a Dilithium public key
#[derive(
	Eq,
	PartialEq,
	Ord,
	PartialOrd,
	Clone,
	Encode,
	Decode,
	RuntimeDebug,
	TypeInfo,
	DecodeWithMemTracking,
)]
pub enum DilithiumSigner {
	Dilithium(DilithiumPublic),
	Dilithium65(Dilithium65Public),
}

#[derive(Debug)]
#[cfg_attr(feature = "std", derive(thiserror::Error))]
pub enum Error {
	#[cfg_attr(feature = "std", error("Failed to generate keypair"))]
	KeyGenerationFailed,
	#[cfg_attr(feature = "std", error("Invalid length"))]
	InvalidLength,
	#[cfg_attr(
		feature = "std",
		error("Entropy must be at least {required} bytes long, got {actual}")
	)]
	InsufficientEntropy { required: usize, actual: usize },
	#[cfg_attr(feature = "std", error("Failed to parse secret key"))]
	InvalidSecretKey,
	#[cfg_attr(feature = "std", error("Failed to parse public key"))]
	InvalidPublicKey,
}

define_dilithium_scheme! {
	variant = Dilithium,
	tag = DilithiumCryptoTag,
	pair = DilithiumPair,
	public = DilithiumPublic,
	signature = DilithiumSignature,
	sig_with_public = DilithiumSignatureWithPublic,
	module = ml_dsa_87,
	verify_fn = verify,
}

define_dilithium_scheme! {
	variant = Dilithium65,
	tag = Dilithium65CryptoTag,
	pair = Dilithium65Pair,
	public = Dilithium65Public,
	signature = Dilithium65Signature,
	sig_with_public = Dilithium65SignatureWithPublic,
	module = ml_dsa_65,
	verify_fn = verify_ml_dsa_65,
}
