use crate::scheme_macro::define_dilithium_scheme;
use codec::{Decode, DecodeWithMemTracking, Encode, MaxEncodedLen};
use scale_info::TypeInfo;
use sp_core::{
	crypto::{PublicBytes, SignatureBytes},
	RuntimeDebug,
};

// Resonance crypto types: Dilithium ML-DSA-87 / ML-DSA-65, modeled after Substrate
// MultiSignature / sr25519. Shared trait impls live in traits.rs; per-scheme
// impls are generated by `define_dilithium_scheme!`.

/// Wrapper around Substrate's PublicBytes to provide Dilithium-specific implementations
///
/// This wrapper enables the implementation of required traits for Dilithium public keys
/// while maintaining compatibility with Substrate's crypto infrastructure.
#[derive(
	Clone,
	Eq,
	PartialEq,
	Hash,
	Encode,
	Decode,
	TypeInfo,
	MaxEncodedLen,
	Ord,
	PartialOrd,
	DecodeWithMemTracking,
)]
pub struct WrappedPublicBytes<const N: usize, SubTag>(pub PublicBytes<N, SubTag>);

/// Wrapper around Substrate's SignatureBytes to provide Dilithium-specific implementations
///
/// This wrapper enables the implementation of required traits for Dilithium signatures
/// while maintaining compatibility with Substrate's crypto infrastructure.
#[derive(
	Clone,
	Eq,
	PartialEq,
	Hash,
	Encode,
	Decode,
	TypeInfo,
	MaxEncodedLen,
	Ord,
	PartialOrd,
	DecodeWithMemTracking,
)]
pub struct WrappedSignatureBytes<const N: usize, SubTag>(pub SignatureBytes<N, SubTag>);

/// Dilithium signature scheme - drop-in replacement for MultiSignature
///
/// Supports ML-DSA-87 (`Dilithium87`) and ML-DSA-65 (`Dilithium65`). New variants
/// must only be appended: existing variant indices are part of the extrinsic
/// wire format.
///
/// Variants are intentionally large (PQ signatures). Boxed fields would keep the
/// same SCALE encoding but add heap traffic on the extrinsic verify path.
#[allow(clippy::large_enum_variant)]
#[derive(
	Eq,
	PartialEq,
	Clone,
	Encode,
	Decode,
	MaxEncodedLen,
	RuntimeDebug,
	TypeInfo,
	DecodeWithMemTracking,
)]
pub enum DilithiumSignatureScheme {
	Dilithium87(Dilithium87SignatureWithPublic),
	Dilithium65(Dilithium65SignatureWithPublic),
	/// ML-DSA-87 signature without the public key, over the domain-separated
	/// message [`sig_only_signing_payload`]`(payload)` rather than the raw
	/// payload. Only verifiable against a public key already cached on chain
	/// (see `pallet-pubkey`); the pure [`Verify`](sp_runtime::traits::Verify)
	/// impl in this crate rejects it.
	Dilithium87SigOnly(Dilithium87Signature),
	/// ML-DSA-65 signature without the public key, over the domain-separated
	/// message [`sig_only_signing_payload`]`(payload)` rather than the raw
	/// payload. Only verifiable against a public key already cached on chain
	/// (see `pallet-pubkey`); the pure [`Verify`](sp_runtime::traits::Verify)
	/// impl in this crate rejects it.
	Dilithium65SigOnly(Dilithium65Signature),
}

/// Domain-separation prefix for `SigOnly` signatures.
///
/// Full `SignatureWithPublic` transactions sign the raw transaction payload;
/// `SigOnly` transactions sign [`sig_only_signing_payload`]`(payload)` =
/// `"qsigonly" ‖ payload`. This makes the signature commit to the encoding
/// form the signer chose: without it, one signature would be valid in both
/// encodings, and any third party (a fee-collecting block author in
/// particular) could re-encode a `SigOnly` extrinsic into the ~2 KB larger
/// full form — inflating the sender's length fee and changing the extrinsic
/// hash the sender is tracking — or shrink a full one, all without touching
/// the signature.
pub const SIG_ONLY_SIGNING_PREFIX: &[u8] = b"qsigonly";

/// The message actually signed and verified for `SigOnly` signatures:
/// [`SIG_ONLY_SIGNING_PREFIX`] followed by the transaction signing payload
/// (the same bytes a full signature would sign).
pub fn sig_only_signing_payload(payload: &[u8]) -> alloc::vec::Vec<u8> {
	let mut msg = alloc::vec::Vec::with_capacity(SIG_ONLY_SIGNING_PREFIX.len() + payload.len());
	msg.extend_from_slice(SIG_ONLY_SIGNING_PREFIX);
	msg.extend_from_slice(payload);
	msg
}

/// Dilithium signer - replacement for MultiSigner
///
/// Identifies the signer of a transaction using a Dilithium public key.
///
/// Variants are intentionally large (PQ public keys). Boxed fields would keep
/// the same SCALE encoding but add heap traffic on hot paths.
#[allow(clippy::large_enum_variant)]
#[derive(
	Eq,
	PartialEq,
	Ord,
	PartialOrd,
	Clone,
	Encode,
	Decode,
	MaxEncodedLen,
	RuntimeDebug,
	TypeInfo,
	DecodeWithMemTracking,
)]
pub enum DilithiumSigner {
	Dilithium87(Dilithium87Public),
	Dilithium65(Dilithium65Public),
}

#[derive(Debug)]
#[cfg_attr(feature = "std", derive(thiserror::Error))]
pub enum Error {
	#[cfg_attr(feature = "std", error("Failed to generate keypair"))]
	KeyGenerationFailed,
	#[cfg_attr(feature = "std", error("Invalid length"))]
	InvalidLength,
	#[cfg_attr(
		feature = "std",
		error("Entropy must be at least {required} bytes long, got {actual}")
	)]
	InsufficientEntropy { required: usize, actual: usize },
	#[cfg_attr(feature = "std", error("Failed to parse secret key"))]
	InvalidSecretKey,
	#[cfg_attr(feature = "std", error("Failed to parse public key"))]
	InvalidPublicKey,
}

define_dilithium_scheme! {
	variant = Dilithium87,
	tag = Dilithium87CryptoTag,
	pair = Dilithium87Pair,
	public = Dilithium87Public,
	signature = Dilithium87Signature,
	sig_with_public = Dilithium87SignatureWithPublic,
	module = ml_dsa_87,
	verify_fn = verify_ml_dsa_87,
}

define_dilithium_scheme! {
	variant = Dilithium65,
	tag = Dilithium65CryptoTag,
	pair = Dilithium65Pair,
	public = Dilithium65Public,
	signature = Dilithium65Signature,
	sig_with_public = Dilithium65SignatureWithPublic,
	module = ml_dsa_65,
	verify_fn = verify_ml_dsa_65,
}
